//! Runs the built binary against a realistic slicer file and checks the
//! resulting G-code is still coherent.
//!
//! Every run also goes through [`nozzle`], which replays the result and refuses
//! a file the toolhead cannot execute. It is wired into [`run_bare`] and
//! [`run_with_env`] rather than into the tests, because those are the only two
//! places this file starts the binary: a test added later cannot skip it
//! without going out of its way, and one that changes what a transform writes
//! is checked against a printer whether or not its author thought to.

mod nozzle;

use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::atomic::{AtomicU32, Ordering};
use std::{env, fs};

use corbel::brick;

const BIN: &str = env!("CARGO_BIN_EXE_corbel");

/// Three layers of PrusaSlicer-flavoured output: an external perimeter, two
/// internal perimeter loops and some sparse infill, with solid infill top and
/// bottom.
fn sample_gcode() -> String {
    gcode_at(&[0.2, 0.4, 0.6, 0.8, 1.0])
}

/// [`sample_gcode`] sliced so that each layer tops out at the given plane, so
/// a file whose slicer varied the height can be driven through the binary.
fn gcode_at(planes: &[f64]) -> String {
    let mut text = String::from(
        "; generated by PrusaSlicer\n\
         M83 ; extruder relative mode\n\
         ; layer_height = 0.2\n",
    );
    for (index, z) in planes.iter().copied().enumerate() {
        text.push_str(";LAYER_CHANGE\n");
        text.push_str(&format!("G1 Z{z:.3} F9000\n"));
        text.push_str(";TYPE:External perimeter\n");
        text.push_str("G1 X0 Y0 F9000\n");
        for (x, y) in [(20.0, 0.0), (20.0, 20.0), (0.0, 20.0), (0.0, 0.0)] {
            text.push_str(&format!("G1 X{x:.3} Y{y:.3} E0.66000\n"));
        }
        text.push_str(";TYPE:Perimeter\n");
        for inset in [0.45_f64, 0.90] {
            text.push_str(&format!("G1 X{inset:.3} Y{inset:.3} F9000\n"));
            let far = 20.0 - inset;
            for (x, y) in [(far, inset), (far, far), (inset, far), (inset, inset)] {
                text.push_str(&format!("G1 X{x:.3} Y{y:.3} E0.64000\n"));
            }
        }
        let solid = index == 0 || index + 1 == planes.len();
        text.push_str(if solid {
            ";TYPE:Solid infill\n"
        } else {
            ";TYPE:Internal infill\n"
        });
        text.push_str("G1 X2 Y2 F9000\n");
        text.push_str("G1 X18 Y18 E1.20000\n");
    }
    text.push_str("M104 S0\n");
    text
}

struct Sandbox(PathBuf);

impl Sandbox {
    fn new(label: &str) -> Self {
        static COUNTER: AtomicU32 = AtomicU32::new(0);
        let id = COUNTER.fetch_add(1, Ordering::Relaxed);
        let path = env::temp_dir().join(format!("corbel-{label}-{}-{id}", std::process::id()));
        fs::create_dir_all(&path).expect("create sandbox");
        Self(path)
    }

    fn with_gcode(&self, contents: &str) -> PathBuf {
        self.with_bytes(contents.as_bytes())
    }

    fn with_bytes(&self, contents: &[u8]) -> PathBuf {
        self.with_named("part.gcode", contents)
    }

    fn with_named(&self, name: &str, contents: &[u8]) -> PathBuf {
        let path = self.0.join(name);
        fs::write(&path, contents).expect("write sample");
        path
    }

    fn path(&self) -> &Path {
        &self.0
    }
}

impl Drop for Sandbox {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

/// Runs the binary with whichever transforms the arguments name, defaulting to
/// both.
///
/// Naming one is mandatory, and every test here that names neither was written
/// against a build where naming neither meant both, so that is what it still
/// means to them. [`run_bare`] is what passes the command line through
/// untouched, and what checks that a run naming nothing is refused.
fn run(args: &[&str]) -> std::process::Output {
    run_bare(&with_transforms(args))
}

/// Runs the binary with exactly the arguments given and nothing added.
fn run_bare(args: &[&str]) -> std::process::Output {
    let output = Command::new(BIN).args(args).output().expect("run binary");
    assert_survivable(args, &output);
    output
}

fn with_transforms<'a>(args: &[&'a str]) -> Vec<&'a str> {
    let mut all = Vec::with_capacity(args.len() + 2);
    if !args.iter().any(|arg| *arg == "--bricks" || *arg == "--zaa") {
        all.extend(["--bricks", "--zaa"]);
    }
    all.extend_from_slice(args);
    all
}

/// Runs the binary the way a slicer would, with the print configuration
/// exported into the environment.
fn run_with_env(args: &[&str], settings: &[(&str, &str)]) -> std::process::Output {
    let args = with_transforms(args);
    let output = Command::new(BIN)
        .args(&args)
        .envs(settings.iter().copied())
        .output()
        .expect("run binary");
    let borrowed: Vec<&str> = args.to_vec();
    assert_survivable(&borrowed, &output);
    output
}

/// Replays a nozzle over whatever that run wrote.
///
/// A run that failed wrote nothing, and a binary container is checked by
/// tests/binary_gcode.rs against Prusa's own reference files instead. A run
/// carrying `--force` is not policed either: that switch is the user
/// overriding a guard this tool put there, and processing a file a second time
/// compounds what the first one did — 122 µm against the 88 a single run
/// leaves.
///
/// What is left is every plain G-code file this suite produces, and the bar
/// depends on which transform wrote it. Bricking has to leave none: it chooses
/// the order its own beads go down in. The surface transform cannot — see
/// [`SURFACE_CREST`].
fn assert_survivable(args: &[&str], output: &std::process::Output) {
    if !output.status.success() || args.contains(&"--force") {
        return;
    }
    let Some(path) = wrote(args) else {
        return;
    };
    let Ok(text) = fs::read_to_string(&path) else {
        return;
    };
    // The ledger needs the input as well, and only a run given `--output`
    // still has one: the default target is the file itself.
    if let Some(source) = args
        .iter()
        .position(|arg| *arg == "--output")
        .and_then(|at| args.get(at + 2))
        .and_then(|input| fs::read_to_string(input).ok())
    {
        let faults = nozzle::faults(
            &nozzle::ledger(&source),
            &nozzle::ledger(&text),
            // What a run says about its flow accounts for bricking alone. The
            // surface transform re-meters what it reshapes on top of that, so
            // the claim no longer describes the whole change.
            (!args.contains(&"--zaa"))
                .then(|| String::from_utf8_lossy(&output.stderr).into_owned())
                .as_deref(),
        );
        assert!(
            faults.is_empty(),
            "{args:?}: {} of what must survive did not\n  {}",
            faults.len(),
            faults.join("\n  ")
        );
    }
    let report = nozzle::inspect(&text);
    assert!(
        report.under_the_bed.is_empty(),
        "{args:?}: {} moves go under the plate",
        report.under_the_bed.len()
    );
    assert!(
        report.dragged.is_empty(),
        "{args:?}: {} beads are dragged, longest {:.1} mm\n{}",
        report.dragged.len(),
        report
            .dragged
            .iter()
            .map(|drag| drag.span)
            .fold(0.0_f64, f64::max),
        report.dragged.first().map_or(String::new(), |drag| format!(
            "  line {}: {}",
            drag.line,
            drag.text.trim()
        ))
    );
    let allowed = match args.contains(&"--zaa") {
        true => report.nozzle.layer * SURFACE_CREST,
        false => 0.0,
    };
    assert!(
        report.worst() <= allowed,
        "{args:?}: a crest {:.0} um deep, over the {:.0} um allowed here\n{}",
        report.worst() * 1000.0,
        allowed * 1000.0,
        report
            .plunges
            .iter()
            .max_by(|left, right| left.depth().total_cmp(&right.depth()))
            .map_or(String::new(), |plunge| format!(
                "  line {}: {}",
                plunge.line,
                plunge.text.trim()
            ))
    );
}

/// How deep a crest the surface transform may leave, as a share of the layer.
///
/// Half a layer is its own amplitude: it moves a bead by up to that either way
/// from the plane, so a bead at one extreme beside one left on the plane is
/// the worst a single run can build. It is not zero and cannot be — six ways
/// of trying to make it zero are recorded in README.md, each measured and each
/// refuted. What this bar does hold is the discipline that brought it here:
/// before the climb was bounded to a bead width, a whole file reached 156 µm,
/// which is more than the amplitude and so more than the geometry can excuse.
const SURFACE_CREST: f64 = 0.5;

/// Where a run put its result: what `--output` names, or the input itself,
/// since a run without one rewrites the file in place.
fn wrote(args: &[&str]) -> Option<PathBuf> {
    if let Some(at) = args
        .iter()
        .position(|arg| *arg == "--output" || *arg == "-o")
    {
        return args.get(at + 1).map(PathBuf::from);
    }
    args.iter()
        .rev()
        .map(PathBuf::from)
        .find(|arg| arg.is_file())
}

/// Every non-comment line must still look like G-code, and no coordinate may be
/// NaN or infinite.
fn assert_wellformed(gcode: &str) {
    for line in gcode.lines() {
        let body = line.split(';').next().unwrap_or("").trim();
        if body.is_empty() {
            continue;
        }
        assert!(
            body.starts_with(['G', 'M', 'T']),
            "unexpected command: {line}"
        );
        for word in body.split_whitespace().skip(1) {
            let (letter, value) = word.split_at(1);
            if !matches!(letter, "X" | "Y" | "Z" | "E" | "F") {
                continue;
            }
            let parsed: f64 = value.parse().unwrap_or_else(|_| panic!("bad word: {line}"));
            assert!(parsed.is_finite(), "non-finite value: {line}");
        }
    }
}

#[test]
fn brick_rewrites_the_file_in_place() {
    let sandbox = Sandbox::new("brick-inplace");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);

    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert_ne!(result, source, "file should have been modified");
    assert_wellformed(&result);
    assert!(result.contains("corbel brick raised"));
    // No reset: a raised loop is the last bead of its layer, and the layer
    // change that follows commands the next plane itself.
    assert!(!result.contains("corbel brick reset"), "{result}");
}

#[test]
fn brick_leaves_infill_untouched_and_meters_every_wall() {
    let sandbox = Sandbox::new("brick-untouched");
    let path = sandbox.with_gcode(&sample_gcode());
    run(&[path.to_str().unwrap()]);

    let result = fs::read_to_string(&path).expect("read result");
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "only the bed layer's visible wall may be left as sliced"
    );
    assert_eq!(
        result.matches("E1.20000").count(),
        5,
        "infill extrusions must be unchanged"
    );
}

#[test]
fn brick_never_leaves_the_nozzle_raised_into_the_next_region() {
    let sandbox = Sandbox::new("brick-z");
    let path = sandbox.with_gcode(&sample_gcode());
    run(&[path.to_str().unwrap()]);
    let result = fs::read_to_string(&path).expect("read result");

    let mut z = 0.0_f64;
    let mut layer_z = 0.0_f64;
    for line in result.lines() {
        if let Some(rest) = line.strip_prefix("G1 Z") {
            z = rest
                .split_whitespace()
                .next()
                .and_then(|value| value.parse().ok())
                .expect("Z value");
            if !line.contains("corbel") {
                layer_z = z;
            }
        }
        if line.starts_with(";TYPE:") && !line.contains("Perimeter") {
            assert_eq!(z, layer_z, "entered {line} while raised");
        }
    }
}

#[test]
fn a_second_run_over_the_same_file_is_refused() {
    let sandbox = Sandbox::new("rerun");
    let path = sandbox.with_gcode(&sample_gcode());
    let file = path.to_str().unwrap();

    assert!(run(&[file]).status.success());
    let once = fs::read_to_string(&path).expect("read result");

    let output = run(&[file]);
    assert!(!output.status.success(), "a repeat run must fail");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("has already been bricked"), "{report}");
    assert_eq!(
        fs::read_to_string(&path).unwrap(),
        once,
        "a refused run must leave the file alone"
    );

    let output = run(&["--force", file]);
    assert!(output.status.success(), "--force overrides: {output:?}");
    assert_ne!(fs::read_to_string(&path).unwrap(), once);
}

/// The wave transform was removed. A slicer still configured to call it has to
/// be told, rather than have its file handed back silently unprocessed.
#[test]
fn the_wave_transform_is_gone() {
    let sandbox = Sandbox::new("no-wave");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);
    let file = path.to_str().unwrap();

    for args in [vec!["wave", file], vec!["wave", "--amplitude", "0.3", file]] {
        let output = run(&args);
        assert!(!output.status.success(), "{args:?} was accepted");
        assert_eq!(
            fs::read_to_string(&path).unwrap(),
            source,
            "{args:?} touched the file"
        );
    }

    let output = run(&["--help"]);
    let help = String::from_utf8_lossy(&output.stdout);
    assert!(!help.contains("wave"), "{help}");
}

/// The version comes from the tag the release workflow stamped in, so a build
/// nobody released says "dev" rather than a number kept in the source.
#[test]
fn the_version_comes_from_the_release_tag() {
    let expected = option_env!("CORBEL_VERSION").unwrap_or("dev");
    let output = run(&["--version"]);
    assert!(output.status.success(), "{output:?}");
    assert_eq!(
        String::from_utf8_lossy(&output.stdout).trim(),
        format!("corbel {expected}")
    );
}

#[test]
fn output_flag_leaves_the_input_alone() {
    let sandbox = Sandbox::new("output-flag");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);
    let target = sandbox.path().join("out.gcode");

    let output = run(&["-o", target.to_str().unwrap(), path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");
    assert_eq!(fs::read_to_string(&path).unwrap(), source);
    assert!(fs::read_to_string(&target).unwrap().contains("corbel"));
}

#[test]
fn no_temporary_files_are_left_behind() {
    let sandbox = Sandbox::new("atomic");
    let path = sandbox.with_gcode(&sample_gcode());
    run(&[path.to_str().unwrap()]);

    let leftovers: Vec<_> = fs::read_dir(sandbox.path())
        .unwrap()
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name())
        .filter(|name| name != "part.gcode")
        .collect();
    assert!(leftovers.is_empty(), "left behind {leftovers:?}");
}

#[test]
fn a_missing_file_fails_with_a_readable_message() {
    let output = run(&["/nonexistent/part.gcode"]);
    assert!(!output.status.success());
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("/nonexistent/part.gcode"), "{stderr}");
}

/// A rewrite is a fresh file renamed over the original, so it starts from the
/// process umask rather than from the permissions the user chose.
#[cfg(unix)]
#[test]
fn a_rewrite_keeps_the_permissions_the_file_had() {
    use std::os::unix::fs::PermissionsExt;

    let sandbox = Sandbox::new("mode");
    let path = sandbox.with_gcode(&sample_gcode());
    fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).expect("chmod");

    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let mode = |path: &Path| fs::metadata(path).expect("stat").permissions().mode() & 0o777;
    assert_eq!(mode(&path), 0o600, "an in-place rewrite widened the file");

    // A new destination has no permissions of its own, so it takes the input's
    // rather than leaving a private file's contents world readable.
    let target = sandbox.path().join("copy.gcode");
    let output = run(&[
        "--force",
        "-o",
        target.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");
    assert_eq!(mode(&target), 0o600, "a copy widened the file");
}

/// A bead laid on the build plate is pressed against the plate rather than
/// against a layer, so raising it presses nothing and the extra flow it would
/// need spreads sideways. There is no seam under it to stagger either. On a
/// Benchy this filled in the bottom nameplate, which is one layer deep.
#[test]
fn the_layer_laid_on_the_bed_is_left_exactly_as_sliced() {
    let sandbox = Sandbox::new("bed-layer");
    let path = sandbox.with_gcode(&sample_gcode());
    let file = path.to_str().unwrap();

    let output = run_with_env(
        &[file],
        &[
            ("SLIC3R_LAYER_HEIGHT", "0.2"),
            ("SLIC3R_FIRST_LAYER_HEIGHT", "0.3"),
        ],
    );
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert_wellformed(&result);
    let bed: String = result
        .lines()
        .take_while(|line| !line.contains("Z0.4"))
        .collect::<Vec<_>>()
        .join("\n");
    assert!(
        !bed.contains("corbel"),
        "the bed layer must come through untouched:\n{bed}"
    );
}

#[test]
fn a_comment_that_is_not_utf8_does_not_stop_the_transform() {
    let sandbox = Sandbox::new("latin1");
    // Slicers copy object names into comments in the host's encoding, so a file
    // of otherwise plain ASCII G-code can carry a stray byte.
    let mut source = sample_gcode().into_bytes();
    let mut named = b"; printing object Caf\xe9\n".to_vec();
    named.append(&mut source);
    let path = sandbox.with_bytes(&named);

    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let raw = fs::read(&path).expect("read result");
    // The byte itself comes back, not a replacement character: the file is the
    // user's only copy and a comment neither transform touched must be the
    // bytes it arrived as, exactly as its line endings are.
    assert!(
        raw.starts_with(b"; printing object Caf\xe9\n"),
        "{:?}",
        String::from_utf8_lossy(&raw[..40.min(raw.len())])
    );
    let result = String::from_utf8_lossy(&raw).into_owned();
    assert_wellformed(&result);
    assert!(result.contains("corbel brick raised"), "{result}");
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "only the bed layer's visible wall may be left as sliced"
    );
}

/// The same byte in a comment on a bead the transform *does* rewrite. Only the
/// numbers it edits may change; everything either side of them is copied.
#[test]
fn a_rewritten_line_keeps_the_bytes_of_its_own_comment() {
    let sandbox = Sandbox::new("latin1-move");
    // A hidden-wall bead, which is re-metered wherever its loop is raised.
    let source = sample_gcode().replacen("E0.64000\n", "E0.64000 ; note\n", 1);
    let mut bytes = source.into_bytes();
    let at = bytes
        .windows(4)
        .position(|window| window == b"note")
        .expect("the marker is in the fixture");
    bytes[at] = 0xe9;
    let path = sandbox.with_bytes(&bytes);

    assert!(run(&[path.to_str().unwrap()]).status.success());
    let raw = fs::read(&path).expect("read result");
    assert_eq!(
        raw.iter().filter(|byte| **byte == 0xe9).count(),
        1,
        "the comment's own byte survived being re-metered"
    );
    assert!(
        raw.windows(6).any(|window| window == b"; \xe9ote"),
        "the comment is otherwise intact"
    );
}

#[test]
fn a_wall_closed_by_a_solid_surface_partway_up_is_left_flat() {
    // A shoulder. The right-hand column of wall stops at the third layer and
    // a solid surface is printed over it at the fourth, while the left-hand
    // one carries on to the top. A bead left raised under that surface takes
    // half the gap the slicer metered a whole layer of material for.
    let mut text = String::from(
        "; generated by PrusaSlicer\n\
         M83 ; extruder relative mode\n\
         ; layer_height = 0.2\n",
    );
    for (index, z) in [0.2, 0.4, 0.6, 0.8, 1.0].iter().enumerate() {
        text.push_str(&format!(
            ";LAYER_CHANGE\nG1 Z{z:.3} F9000\n;TYPE:Perimeter\n"
        ));
        let shoulder = index < 3;
        for origin in if shoulder {
            &[0.0, 40.0][..]
        } else {
            &[0.0][..]
        } {
            for inset in [0.45_f64, 0.90] {
                let (near, far) = (origin + inset, origin + 20.0 - inset);
                text.push_str(&format!("G1 X{near:.3} Y{near:.3} F9000\n"));
                for (x, y) in [(far, near), (far, far), (near, far), (near, near)] {
                    text.push_str(&format!("G1 X{x:.3} Y{y:.3} E0.64000\n"));
                }
            }
        }
        if !shoulder {
            text.push_str(";TYPE:Solid infill\nG1 X42 Y42 F9000\nG1 X58 Y58 E1.20000\n");
        }
    }
    text.push_str("M104 S0\n");

    let sandbox = Sandbox::new("shoulder");
    let path = sandbox.with_gcode(&text);
    let output = run(&["--verbose", path.to_str().unwrap()]);
    assert!(output.status.success());
    let out = std::fs::read_to_string(&path).unwrap();
    assert_wellformed(&out);

    // Which wall a bead belongs to is where it is, not where it sits in the
    // text: loops are written lowest first and a raised one waits for the end
    // of its layer, so neither wall's beads are a contiguous stretch.
    let layers: Vec<&str> = out.split(";LAYER_CHANGE").collect();
    let raised_in = |layer: usize, shoulder: bool| {
        let mut z = 0.0_f64;
        let mut plane = 0.0_f64;
        let mut found = false;
        for line in layers[layer].lines() {
            let words: Vec<&str> = line
                .split(';')
                .next()
                .unwrap_or("")
                .split_whitespace()
                .collect();
            let word = |letter: char| {
                words
                    .iter()
                    .find(|w| w.starts_with(letter))
                    .and_then(|w| w[1..].parse::<f64>().ok())
            };
            if let Some(height) = word('Z') {
                z = height;
                if !line.contains("corbel") {
                    plane = height;
                }
            }
            let Some(x) = word('X') else { continue };
            if word('E').is_some_and(|e| e > 0.0) && (x >= 40.0) == shoulder {
                found |= z > plane + 1e-9;
            }
        }
        found
    };
    assert!(
        !raised_in(3, true),
        "the wall that stops must finish on the plane: {}",
        layers[3]
    );
    assert!(
        raised_in(2, true),
        "while the layer below it still bricks: {}",
        layers[2]
    );
    assert!(
        raised_in(3, false),
        "and so does the wall that carries on, on the same layer: {}",
        layers[3]
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("left flat where the wall ends"), "{stderr}");
}

#[test]
fn verbose_reports_a_summary() {
    let sandbox = Sandbox::new("verbose");
    let path = sandbox.with_gcode(&format!(
        "; inner_wall_line_width = 0.45\n{}",
        sample_gcode()
    ));
    let output = run(&["--verbose", path.to_str().unwrap()]);

    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("5 layers"), "{stderr}");
    // Three walls a layer, the visible one included.
    assert!(stderr.contains("15 perimeter loops"), "{stderr}");
    // One per layer, less the bed layer, which is never raised, and the top
    // one, which caps the wall flat.
    assert!(stderr.contains("3 raised"), "{stderr}");
    assert!(stderr.contains("in raised loops"), "{stderr}");
    assert!(
        stderr.contains("a flow of 1.025"),
        "the flow that was applied must be priced in the summary: {stderr}"
    );
}

/// A file that never states how wide its walls were metered still gets a flow,
/// but it is the shipped default rather than this print's own geometry, and
/// the difference has to be visible or "read off the file" is a claim the user
/// cannot check.
#[test]
fn a_file_that_states_no_width_says_the_flow_is_a_default() {
    let sandbox = Sandbox::new("no-width");
    let path = sandbox.with_gcode(&sample_gcode());
    let output = run(&["--verbose", path.to_str().unwrap()]);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("states no internal wall width"), "{stderr}");

    let stated = Sandbox::new("width");
    let path = stated.with_gcode(&format!(
        "; inner_wall_line_width = 0.45\n{}",
        sample_gcode()
    ));
    let output = run(&["--verbose", path.to_str().unwrap()]);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        !stderr.contains("states no internal wall width"),
        "{stderr}"
    );
}

/// Nothing has to be passed for the walls to be metered: the flow comes off
/// the geometry the file states about itself, so a profile laying narrow beads
/// through a fine nozzle pays more than one laying wide ones.
#[test]
fn the_flow_is_read_off_the_file_with_no_flag_given() {
    let report = |stated: &str| {
        let sandbox = Sandbox::new("derived-flow");
        let path = sandbox.with_gcode(&format!(
            "; nozzle_diameter = 0.4\n; inner_wall_line_width = {stated}\n{}",
            sample_gcode()
        ));
        let output = run(&["--verbose", path.to_str().unwrap()]);
        String::from_utf8_lossy(&output.stderr).into_owned()
    };
    let narrow = report("0.35");
    assert!(narrow.contains("a flow of 1.033"), "{narrow}");
    let wide = report("0.65");
    assert!(wide.contains("a flow of 1.017"), "{wide}");
    // A percentage is of the nozzle, and 0.4 mm of it is the reference wall.
    let share = report("112.5%");
    assert!(share.contains("a flow of 1.025"), "{share}");
}

/// The dial names the extra a wall takes where the layer is as thick as the
/// nozzle, so a 0.2 mm layer through a 0.4 mm nozzle takes half of it. The
/// visible wall moves with it so the part keeps its dimensions either way.
#[test]
fn the_extra_flow_dial_sets_the_slope_the_geometry_follows() {
    let report = |percent: &str| {
        let sandbox = Sandbox::new("extra-flow");
        let path = sandbox.with_gcode(&format!(
            "; inner_wall_line_width = 0.45\n{}",
            sample_gcode()
        ));
        let output = run(&["--extra-flow", percent, "--verbose", path.to_str().unwrap()]);
        assert!(output.status.success(), "{output:?}");
        String::from_utf8_lossy(&output.stderr).into_owned()
    };
    let half = report("2.5");
    assert!(half.contains("a flow of 1.012"), "{half}");
    assert!(half.contains("--extra-flow 2.5%"), "{half}");

    let more = report("10");
    assert!(more.contains("a flow of 1.050"), "{more}");

    let none = report("0");
    assert!(none.contains("a flow of 1.000"), "{none}");

    // Left alone it is not named, because there is nothing to explain.
    let sandbox = Sandbox::new("extra-flow-default");
    let path = sandbox.with_gcode(&format!(
        "; inner_wall_line_width = 0.45\n{}",
        sample_gcode()
    ));
    let output = run(&["--verbose", path.to_str().unwrap()]);
    let plain = String::from_utf8_lossy(&output.stderr);
    assert!(plain.contains("a flow of 1.025"), "{plain}");
    assert!(!plain.contains("--extra-flow"), "{plain}");
}

/// A slicer running this as a post-processing script exports its whole
/// configuration, and what it says outranks the copy in the file.
#[test]
fn the_slicer_environment_states_the_width_too() {
    let sandbox = Sandbox::new("env-width");
    let path = sandbox.with_gcode(&format!(
        "; inner_wall_line_width = 0.45\n{}",
        sample_gcode()
    ));
    let output = run_with_env(
        &["--verbose", path.to_str().unwrap()],
        &[
            ("SLIC3R_NOZZLE_DIAMETER", "0.4"),
            ("SLIC3R_PERIMETER_EXTRUSION_WIDTH", "87.5%"),
        ],
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("a flow of 1.033"), "{stderr}");
}

/// The stagger is half a layer, so the step it leaves grows with the layer
/// height while the nozzle that has to clear it does not. Nothing here can fix
/// that without giving up the stagger, so it is said plainly instead.
#[test]
fn a_layer_more_than_half_the_nozzle_is_warned_about() {
    let sandbox = Sandbox::new("thick-layer");
    let path = sandbox.with_gcode(&format!(
        "; nozzle_diameter = 0.4\n; layer_height = 0.3\n{}",
        gcode_at(&[0.3, 0.6, 0.9, 1.2, 1.5])
    ));
    let output = run(&[path.to_str().unwrap()]);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("warning"), "{stderr}");
    assert!(stderr.contains("0.4 mm nozzle"), "{stderr}");

    // The same file at a layer the nozzle can clear says nothing.
    let quiet = Sandbox::new("thin-layer");
    let path = quiet.with_gcode(&format!("; nozzle_diameter = 0.4\n{}", sample_gcode()));
    let output = run(&[path.to_str().unwrap()]);
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(!stderr.contains("warning"), "{stderr}");
}

/// The flow is for the walls, the visible one included: every wall above the
/// bed is re-metered, and nothing that is not a wall — the solid surfaces that
/// close the part top and bottom, the infill between them — is touched.
#[test]
fn every_wall_above_the_bed_is_rescaled_and_nothing_else_is() {
    let sandbox = Sandbox::new("walls");
    let path = sandbox.with_gcode(&sample_gcode());
    let output = run(&["--verbose", path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert_wellformed(&result);
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "only the bed layer's visible wall may be left as sliced"
    );
    assert_eq!(
        result.matches("E1.20000").count(),
        5,
        "infill and solid surfaces must be unchanged"
    );
    // Eight of the file's forty internal perimeter moves are on the bed, and
    // those are the only ones left as sliced.
    assert_eq!(
        result.matches("E0.64000").count(),
        8,
        "every wall above the bed must be re-metered:\n{result}"
    );
}

/// A file handed no flags at all still gets the shipped flow.
#[test]
fn the_shipped_default_rescales_the_walls() {
    let sandbox = Sandbox::new("default-flow");
    let path = sandbox.with_gcode(&sample_gcode());
    assert!(run(&[path.to_str().unwrap()]).status.success());

    let result = fs::read_to_string(&path).expect("read result");
    // 0.64 at 1.025, on every internal perimeter move but the bed layer's and
    // those the raise meters for a step of their own: 1.25 while a column
    // climbs, 0.5 where one is capped.
    assert_eq!(
        result.matches("E0.65600").count(),
        20,
        "the walls metered over:\n{result}"
    );
    assert_eq!(result.matches("E0.82000").count(), 8, "climbing");
    assert_eq!(result.matches("E0.32800").count(), 4, "capped");
    assert_eq!(result.matches("E0.64000").count(), 8, "the bed layer");
    assert_eq!(
        result.matches("E0.67616").count(),
        16,
        "the visible wall metered over as well, and shortened by coming in"
    );
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "and only the bed layer's left as sliced"
    );
}

/// The visible wall is brought toward the loop behind it by half of what the
/// multiplier would have added as flow, so the joint against it closes without
/// the part growing. It needs the width the wall was metered at, which only the
/// file can state.
#[test]
fn the_visible_wall_is_drawn_in_where_the_file_states_its_width() {
    let sandbox = Sandbox::new("skin-inset");
    let stated = sample_gcode().replace(
        "; layer_height = 0.2\n",
        "; layer_height = 0.2\n; external_perimeter_extrusion_width = 0.4\n",
    );
    let path = sandbox.with_gcode(&stated);
    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    assert_wellformed(&result);
    // A 0.4 mm wall is laid 0.357 mm from its neighbour at these layers, so at
    // the flow its geometry asks for, 1.025, it widens by 0.0089 and comes in
    // by half of that on all four sides, landing its outer face back where it
    // was. Four of the file's five layers: the one on the build plate is left
    // exactly as sliced.
    assert_eq!(
        result.matches("G1 X19.996 Y0.004 ").count(),
        4,
        "the visible wall must come in by the offset:\n{result}"
    );
    assert_eq!(
        result.matches("E0.67620").count(),
        16,
        "and carry the filament its new width asks for"
    );
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "only the bed layer's four beads may be left as sliced"
    );
    assert_eq!(
        result.matches("G1 X20.000 Y0.000 E0.66000").count(),
        1,
        "and only on the bed layer"
    );
}

/// A file that states no width still has its visible wall drawn in. Scaling a
/// wall without moving it grows the part by half of what the wall gained, so
/// the offset falls back to the same reference profile the flow does rather
/// than to nothing. Cura writes its settings in a form nothing else parses,
/// which is the file this is about.
#[test]
fn a_file_that_states_no_wall_width_falls_back_to_the_reference_profile() {
    let sandbox = Sandbox::new("skin-untouched");
    let path = sandbox.with_gcode(&sample_gcode());
    assert!(run(&[path.to_str().unwrap()]).status.success());

    let result = fs::read_to_string(&path).expect("read result");
    assert_eq!(
        result.matches("E0.66000").count(),
        4,
        "only the bed layer's visible wall may be left as sliced:\n{result}"
    );
    // 0.45 mm at 0.2 mm layers and a flow of 1.025 comes in by 0.005.
    assert_eq!(
        result.matches("G1 X19.995 Y0.005 ").count(),
        4,
        "and the rest must come in by the reference profile's offset:\n{result}"
    );
    assert_eq!(
        result.matches("G1 X20.000 Y0.000 E").count(),
        1,
        "leaving only the bed layer where the slicer drew it"
    );
}

#[test]
fn help_and_version_are_available() {
    for command in [["--help"], ["--version"]] {
        let output = run(&command);
        assert!(output.status.success(), "{command:?} failed");
        assert!(!output.stdout.is_empty());
    }
    assert!(run(&["--help"]).status.success());
}

#[test]
fn the_slicer_environment_supplies_the_layer_height() {
    let sandbox = Sandbox::new("env-layer-height");
    // Without the comment the Z steps would measure 0.2, so 0.3 can only have
    // come from the environment.
    let path = sandbox.with_gcode(&sample_gcode().replace("; layer_height = 0.2\n", ""));
    let file = path.to_str().unwrap();

    let output = run_with_env(&["--verbose", file], &[("SLIC3R_LAYER_HEIGHT", "0.3")]);
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("raised by 0.150 mm"), "{report}");
    assert!(!report.contains("warning"), "{report}");
}

/// An adaptive slice has no one layer height, so the nominal a slicer exports
/// describes none of its layers and cannot stand in for measuring them.
#[test]
fn a_varied_layer_height_is_measured_rather_than_taken_from_the_slicer() {
    let sandbox = Sandbox::new("varied-layer-height");
    // Every layer is 0.2 but the fourth, which is 0.1, so a raise of half the
    // exported 0.3 would be one and a half times its own height.
    let planes = [0.2, 0.4, 0.6, 0.7, 0.9];
    let path = sandbox.with_gcode(&gcode_at(&planes));
    let file = path.to_str().unwrap();

    let output = run_with_env(&["--verbose", file], &[("SLIC3R_LAYER_HEIGHT", "0.3")]);
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("varied the layer height"), "{report}");
    assert!(
        report.contains("raised by 0.050 to 0.100 mm"),
        "each layer takes its own half, not half of the exported 0.3: {report}"
    );
}

#[test]
fn slicer_settings_that_defeat_the_transform_are_reported() {
    let sandbox = Sandbox::new("env-warnings");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(
        &[path.to_str().unwrap()],
        &[
            ("SLIC3R_WALL_SEQUENCE", "inner wall/outer wall"),
            ("SLIC3R_WALL_LOOPS", "1"),
            ("SLIC3R_SPIRAL_MODE", "1"),
            ("SLIC3R_ENABLE_ARC_FITTING", "1"),
        ],
    );
    assert!(output.status.success(), "{output:?}");

    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("spiral vase"), "{report}");
    assert!(
        !report.contains("arc fitting"),
        "arc fitting is handled, so it is not a setting that defeats anything: {report}"
    );
    assert!(report.contains("1 wall(s)"), "{report}");
}

/// Two walls leave exactly one internal perimeter per region. That loop is
/// raised against the external perimeter it was inset from, so the run bricks
/// rather than reporting the file as beyond help.
#[test]
fn two_walls_are_bricked_rather_than_refused() {
    let sandbox = Sandbox::new("env-two-walls");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(
        &["--verbose", path.to_str().unwrap()],
        &[("SLIC3R_PERIMETERS", "2")],
    );
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(!report.contains("wall(s)"), "{report}");
    assert!(report.contains("3 raised"), "{report}");
}

/// One wall is the visible one, with nothing hidden behind it to shift, so the
/// run has to say so rather than report having done nothing.
#[test]
fn a_single_wall_is_reported_as_leaving_nothing_to_raise() {
    let sandbox = Sandbox::new("env-one-wall");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(&[path.to_str().unwrap()], &[("SLIC3R_PERIMETERS", "1")]);
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("1 wall(s)"), "{report}");
    assert!(report.contains("two walls or more"), "{report}");
}

/// Arc fitting is a print setting, so the file carries the evidence even when
/// the tool is run by hand rather than by a slicer. `brick` shifts an arc with
/// the loop around it, so it has nothing to say about one.
#[test]
fn walls_emitted_as_arcs_draw_no_warning() {
    let sandbox = Sandbox::new("arcs");
    let arced = sample_gcode().replace(
        "G1 X19.550 Y19.550 E0.64000",
        "G3 X19.550 Y19.550 I1 J1 E0.64000",
    );
    let path = sandbox.with_gcode(&arced);

    let output = run_with_env(
        &[path.to_str().unwrap()],
        &[("SLIC3R_ENABLE_ARC_FITTING", "1")],
    );
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(!report.contains("arc"), "{report}");
}

#[test]
fn a_well_configured_slicer_draws_no_warnings() {
    let sandbox = Sandbox::new("env-quiet");
    let path = sandbox.with_gcode(&sample_gcode());

    let output = run_with_env(
        &[path.to_str().unwrap()],
        &[
            ("SLIC3R_EXTERNAL_PERIMETERS_FIRST", "1"),
            ("SLIC3R_PERIMETERS", "3"),
            ("SLIC3R_SPIRAL_VASE", "0"),
            ("SLIC3R_ARC_FITTING", "emit_center"),
        ],
    );
    assert!(output.status.success(), "{output:?}");
    let report = String::from_utf8_lossy(&output.stderr);
    assert!(!report.contains("warning"), "{report}");
}

/// The visible wall anchors the alternation by being recognised, not by being
/// counted from one end, so once it is in the contour the order the slicer
/// printed the walls in no longer decides anything. It is still the fallback
/// for a contour that holds no visible wall.
#[test]
fn the_wall_order_no_longer_decides_where_the_alternation_starts() {
    let sandbox = Sandbox::new("wall-order");

    let bricked = |settings: &[(&str, &str)]| {
        let path = sandbox.with_gcode(&sample_gcode());
        let output = run_with_env(&[path.to_str().unwrap()], settings);
        assert!(output.status.success(), "{output:?}");
        let result = fs::read_to_string(&path).expect("read result");
        assert_wellformed(&result);
        result
    };

    assert_eq!(
        bricked(&[("SLIC3R_EXTERNAL_PERIMETERS_FIRST", "1")]),
        bricked(&[("SLIC3R_EXTERNAL_PERIMETERS_FIRST", "0")]),
        "the visible wall anchors the stack whichever end it was printed at"
    );
}

#[test]
fn crlf_input_is_accepted() {
    let sandbox = Sandbox::new("crlf");
    let path = sandbox.with_gcode(&sample_gcode().replace('\n', "\r\n"));
    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&path).expect("read result");
    // A file that arrived with Windows endings leaves with them. This used to
    // assert the opposite — that every `\r` was gone — which is what made a
    // Windows-authored file come back with every line changed.
    assert_eq!(
        result.matches('\n').count(),
        result.matches("\r\n").count(),
        "a bare newline was written into a CRLF file"
    );
    assert_wellformed(&result);
}

/// Both transforms promise that a part they do not touch comes back untouched,
/// and on a Windows-authored file that is a claim about every line: readers
/// strip the `\r` and writers put back a bare `\n`. The last line here carries
/// no ending at all, since one gained on the way out is a changed file too.
#[test]
fn a_crlf_file_with_nothing_to_do_comes_back_byte_for_byte() {
    let sandbox = Sandbox::new("crlf-identical");
    // No perimeter regions and no surface to follow, so neither transform has
    // anything to work on and every line is copied through.
    let source = "; generated by PrusaSlicer\r\n\
                  M83\r\n\
                  ;LAYER_CHANGE\r\n\
                  G1 Z0.200 F9000\r\n\
                  G1 X0 Y0 F9000\r\n\
                  G1 X10 Y0 E0.50000\r\n\
                  ;LAYER_CHANGE\r\n\
                  G1 Z0.400 F9000\r\n\
                  G1 X10 Y10 E0.50000\r\n\
                  M104 S0";
    let path = sandbox.with_bytes(source.as_bytes());

    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");
    assert_eq!(
        fs::read(&path).expect("read result"),
        source.as_bytes(),
        "a file nothing was done to did not come back as it went in"
    );
}

/// A slicer's output directory pointed at shared storage is a symbolic link,
/// and `rename` replaces the link itself rather than the file it stands for:
/// the real file would keep the G-code as it was sliced and the link would be
/// gone.
#[cfg(unix)]
#[test]
fn a_symlinked_file_is_processed_where_it_really_lives() {
    let sandbox = Sandbox::new("symlink");
    let real = sandbox.with_named("real.gcode", sample_gcode().as_bytes());
    let link = sandbox.path().join("part.gcode");
    std::os::unix::fs::symlink(&real, &link).expect("link it");

    let output = run(&[link.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let kind = fs::symlink_metadata(&link).expect("stat").file_type();
    assert!(kind.is_symlink(), "the link was replaced by a regular file");
    assert_eq!(fs::read_link(&link).expect("read the link"), real);

    let result = fs::read_to_string(&real).expect("read the file it points at");
    assert_wellformed(&result);
    assert!(
        result.contains("corbel"),
        "the file the link stands for was never processed"
    );
}

/// A rename publishes a new inode, so every other name hard-linked to the
/// target keeps the file as it was sliced. Nothing in `std` can move them, so
/// the run says so rather than leaving it to be discovered on the printer.
#[cfg(unix)]
#[test]
fn other_names_for_the_same_file_are_reported_rather_than_left_in_silence() {
    let sandbox = Sandbox::new("hard-links");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);
    let also = sandbox.path().join("also.gcode");
    fs::hard_link(&path, &also).expect("hard link");

    let output = run(&[path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("hard-linked"), "{stderr}");
    assert_eq!(
        fs::read_to_string(&also).expect("read the other name"),
        source,
        "the warning describes what actually happened"
    );
}

/// `--output` naming a directory used to put the temporary in that
/// directory's PARENT — `with_file_name` on `/spool/prints` is
/// `/spool/prints.<token>.tmp` — so a whole print was written somewhere the
/// user never named before the rename failed.
#[test]
fn an_output_that_names_a_directory_fails_before_anything_is_written() {
    let sandbox = Sandbox::new("output-directory");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);
    let directory = sandbox.path().join("spool");
    fs::create_dir(&directory).expect("create the directory");

    let output = run(&["-o", directory.to_str().unwrap(), path.to_str().unwrap()]);
    assert!(!output.status.success(), "{output:?}");
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("directory"), "{stderr}");

    assert_eq!(
        fs::read_to_string(&path).unwrap(),
        source,
        "the input moved"
    );
    assert!(
        fs::read_dir(&directory).unwrap().next().is_none(),
        "something was written into the directory"
    );
    let leftovers: Vec<_> = fs::read_dir(sandbox.path())
        .unwrap()
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .filter(|name| name.ends_with(".tmp"))
        .collect();
    assert!(leftovers.is_empty(), "left behind {leftovers:?}");
}

/// `SLIC3R_PP_OUTPUT_NAME` is a file name out of a project or 3MF the user may
/// not have authored, and the slicer exports it exactly as it found it.
#[test]
fn a_name_the_slicer_exports_cannot_reach_the_terminal_as_an_instruction() {
    let sandbox = Sandbox::new("hostile-name");
    let path = sandbox.with_gcode(&sample_gcode());
    let hostile = format!(
        "part\u{1b}[2J\u{1b}]0;taken over\u{7}\u{202e}{}",
        "x".repeat(500)
    );

    let output = run_with_env(
        &["--verbose", path.to_str().unwrap()],
        &[("SLIC3R_PP_OUTPUT_NAME", hostile.as_str())],
    );
    assert!(output.status.success(), "{output:?}");
    assert!(
        !output
            .stderr
            .iter()
            .any(|byte| *byte == 0x1b || *byte == 0x07),
        "an escape code reached the terminal"
    );

    let stderr = String::from_utf8_lossy(&output.stderr);
    let line = stderr
        .lines()
        .find(|line| line.contains("save this as"))
        .expect("the name is still reported");
    assert!(line.contains("part"), "{line}");
    assert!(!line.contains('\u{202e}'), "{line}");
    assert!(
        line.chars().count() < 200,
        "the name buried what was printed after it"
    );
}

/// The binary streams a file through the same transform the library runs over a
/// string, so the two have to agree byte for byte. This is what pins the line
/// reader, the buffered writer and the atomic rename to the reference result.
#[test]
fn streaming_a_file_matches_rewriting_it_in_memory() {
    let sandbox = Sandbox::new("streaming-matches");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);

    let in_memory = brick::apply(&source, &brick::Config::default()).gcode;
    let out = sandbox.path().join("brick.gcode");
    let output = run(&["--output", out.to_str().unwrap(), path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let streamed = fs::read_to_string(&out).expect("read result");
    assert_eq!(streamed, in_memory, "brick diverged from the library");
}

/// Nothing this tool writes may ask the nozzle to go below the build plate.
#[test]
fn no_transform_ever_commands_a_z_below_the_bed() {
    let sandbox = Sandbox::new("below-bed");
    let path = sandbox.with_gcode(&sample_gcode());

    for args in [vec!["plain"], vec!["verbose", "--verbose"]] {
        let out = sandbox.path().join(format!("{}.gcode", args[0]));
        let mut call: Vec<&str> = args[1..].to_vec();
        call.extend(["--output", out.to_str().unwrap(), path.to_str().unwrap()]);
        let output = run(&call);
        assert!(output.status.success(), "{args:?}: {output:?}");

        let result = fs::read_to_string(&out).expect("read result");
        assert_wellformed(&result);
        for line in result.lines() {
            let body = line.split(';').next().unwrap_or("");
            for word in body.split_whitespace().skip(1) {
                if let Some(digits) = word.strip_prefix('Z') {
                    let z: f64 = digits.parse().expect("a number");
                    assert!(z >= 0.0, "{args:?} commanded {line}");
                }
            }
        }
    }
}

/// Numbers are written digit by digit rather than through the standard
/// formatter. A coordinate that sits exactly on a rounding boundary is where
/// the two could part, so the whole binary is checked against a file made of
/// them: every value must read back as the one the formatter would print.
#[test]
fn coordinates_on_a_rounding_boundary_survive_the_binary() {
    let sandbox = Sandbox::new("rounding");

    let mut source = String::from("; layer_height = 0.2\nM83\n");
    for layer in 0..4 {
        let z = 0.2 + f64::from(layer) * 0.2;
        source.push_str(";LAYER_CHANGE\n");
        source.push_str(&format!("G1 Z{z:.3} F600\n"));
        source.push_str(";TYPE:Perimeter\n");
        for inset in [0.0_f64, 0.4375] {
            // Odd sixteenths land exactly on a half-way point at three
            // decimals, where rounding goes to even rather than away from zero.
            let (near, far) = (1.0625 + inset, 9.9375 - inset);
            source.push_str(&format!("G1 X{near} Y{near} F9000\n"));
            for (x, y) in [(far, near), (far, far), (near, far), (near, near)] {
                source.push_str(&format!("G1 X{x} Y{y} E0.53125\n"));
            }
        }
    }
    let path = sandbox.with_gcode(&source);

    let out = sandbox.path().join("brick.gcode");
    let output = run(&["--output", out.to_str().unwrap(), path.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&out).expect("read result");
    assert_wellformed(&result);
    for line in result.lines() {
        let body = line.split(';').next().unwrap_or("");
        for word in body.split_whitespace().skip(1) {
            let (letter, digits) = word.split_at(1);
            if !matches!(letter, "X" | "Y" | "Z" | "E" | "F") {
                continue;
            }
            let value: f64 = digits.parse().expect("a number");
            let decimals = digits.split_once('.').map_or(0, |(_, tail)| tail.len());
            assert_eq!(
                digits,
                format!("{value:.decimals$}"),
                "wrote {word} in: {line}"
            );
        }
    }
}

/// A shallow cone in PrusaSlicer's dialect: a square whose side loses 3 mm a
/// layer, so every layer leaves a 3 mm strip of itself exposed. The strip is
/// covered by the wall stack and then by a top surface, which is what a slicer
/// emits and what a staircase is made of.
fn sloped_gcode(layers: usize) -> String {
    sloped_gcode_at(layers, 0.2)
}

/// The same cone sliced at a stated layer height. How wide a step is worth
/// following is a slope, so the height is what decides whether this file's
/// 3 mm strip is one.
fn sloped_gcode_at(layers: usize, height: f64) -> String {
    let mut text = format!(
        "; generated by PrusaSlicer\n\
         M83 ; extruder relative mode\n\
         ; layer_height = {height}\n\
         ; perimeter_extrusion_width = 0.45\n\
         ; nozzle_diameter = 0.4\n"
    );
    for layer in 0..layers {
        // Three layers of vertical wall before the taper, so bricking has a
        // column to raise and the taper has something under it to slope from.
        let half = 30.0 - 3.0 * layer.saturating_sub(2) as f64;
        text.push_str(";LAYER_CHANGE\n");
        text.push_str(&format!("G1 Z{:.3} F600\n", height * (layer + 1) as f64));
        for (label, half) in [
            (";TYPE:Perimeter\n", half - 0.45),
            (";TYPE:External perimeter\n", half),
        ] {
            text.push_str(label);
            text.push_str(&format!("G1 X{:.3} Y{:.3} F9000\n", -half, -half));
            for (x, y) in [(half, -half), (half, half), (-half, half), (-half, -half)] {
                text.push_str(&format!("G1 X{x:.3} Y{y:.3} E1.00000\n"));
            }
        }
        text.push_str(";TYPE:Top solid infill\n");
        let (inner, outer) = (half - 3.0 + 0.35, half - 0.3);
        for step in 0..5 {
            let x = inner + (outer - inner) * step as f64 / 4.0;
            let (from, to) = if step % 2 == 0 {
                (-6.0, 6.0)
            } else {
                (6.0, -6.0)
            };
            text.push_str(&format!("G1 X{x:.3} Y{from:.3} F9000\n"));
            text.push_str(&format!("G1 X{x:.3} Y{to:.3} E0.35000\n"));
        }
    }
    text.push_str("M104 S0\n");
    text
}

/// The heights every extruding move of a region was commanded at, with the
/// axes each move left unnamed carried forward.
fn heights_of(gcode: &str, region: &str) -> Vec<f64> {
    let (mut z, mut here) = (0.0, false);
    let mut found = Vec::new();
    for line in gcode.lines() {
        let body = line.split(';').next().unwrap_or("").trim();
        if body.is_empty() {
            if let Some(marker) = line.trim().strip_prefix(";TYPE:") {
                here = marker.trim() == region;
            }
            continue;
        }
        for word in body.split_whitespace().skip(1) {
            if let Some(digits) = word.strip_prefix('Z') {
                z = digits.parse().expect("a number");
            }
        }
        let lays = body.contains('E') && (body.contains('X') || body.contains('Y'));
        if here && lays {
            found.push(z);
        }
    }
    found
}

/// The whole point: a shallow top comes out as a ramp rather than a staircase.
/// Every bead with nothing printed over it follows the surface — the wall that
/// shows, the hidden wall behind it and the top itself — and none of them ever
/// stands more than half a layer off its own plane.
#[test]
fn a_shallow_top_is_followed_rather_than_stepped() {
    let sandbox = Sandbox::new("zaa-slope");
    let path = sandbox.with_gcode(&sloped_gcode(6));
    let out = sandbox.path().join("zaa.gcode");
    let output = run(&[
        "--zaa",
        "--verbose",
        "--output",
        out.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&out).expect("read result");
    assert_wellformed(&result);
    assert!(result.contains("corbel zaa surface"));

    for region in ["External perimeter", "Top solid infill"] {
        let heights = heights_of(&result, region);
        assert!(!heights.is_empty(), "{region} is printed");
        let off = heights
            .iter()
            .map(|z| (z * 5.0).round() / 5.0 - z)
            .fold(0.0f64, |worst, off| worst.max(off.abs()));
        assert!(off > 0.02, "{region} follows the surface: {off}");
        assert!(off <= 0.1 + 1e-6, "{region} stays inside its layer: {off}");
    }
    // The hidden wall follows too, since nothing has raised it out from
    // under this run's feet.
    let hidden = heights_of(&result, "Perimeter");
    assert!(!hidden.is_empty(), "the hidden wall is printed");
    let off = hidden
        .iter()
        .map(|z| (z * 5.0).round() / 5.0 - z)
        .fold(0.0f64, |worst, off| worst.max(off.abs()));
    assert!(off > 0.02, "the hidden wall follows the surface: {off}");
    assert!(
        off <= 0.1 + 1e-6,
        "the hidden wall stays inside its layer: {off}"
    );

    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("surface moves on"), "{report}");
}

/// Bricking raises alternate hidden loops half a layer, and the surface
/// transform cannot see which. Lowering a wall onto one would close a gap the
/// slicer metered open, so a run that does both leaves the hidden wall exactly
/// where bricking put it and follows only what it owns outright.
#[test]
fn the_hidden_wall_is_left_alone_when_bricking_is_running_too() {
    let sandbox = Sandbox::new("zaa-bricked");
    let path = sandbox.with_gcode(&sloped_gcode(6));

    let mut heights = Vec::new();
    for (name, switches) in [
        ("bricks", &["--bricks"][..]),
        ("both", &["--bricks", "--zaa"]),
    ] {
        let out = sandbox.path().join(format!("{name}.gcode"));
        let output = run(&[
            switches,
            &["--output", out.to_str().unwrap(), path.to_str().unwrap()],
        ]
        .concat());
        assert!(output.status.success(), "{output:?}");
        let result = fs::read_to_string(&out).expect("read result");
        assert_wellformed(&result);
        heights.push((heights_of(&result, "Perimeter"), result));
    }

    let (bricked, _) = &heights[0];
    let (both, result) = &heights[1];
    assert!(!bricked.is_empty(), "the hidden wall is printed");
    assert_eq!(bricked, both, "the surface transform moved a hidden bead");

    // And it is a run that did something, or the comparison proves nothing.
    let shown = heights_of(result, "External perimeter");
    assert!(
        shown
            .iter()
            .any(|z| ((z * 5.0).round() / 5.0 - z).abs() > 0.02),
        "the wall that shows still follows the surface"
    );
}

/// The same guard, across two runs of the binary rather than one. A file
/// carries the stamp of the bricking an earlier run did, so the bead under a
/// hidden wall can stand half a layer proud whether or not `--bricks` is named
/// this time. Reading the switch alone hands the file to a surface pass that
/// believes it owns walls it does not.
#[test]
fn a_file_bricked_by_an_earlier_run_still_owns_its_hidden_walls() {
    let sandbox = Sandbox::new("zaa-was-bricked");
    let path = sandbox.with_gcode(&sloped_gcode(6));

    let bricked = sandbox.path().join("bricked.gcode");
    let output = run(&[
        "--bricks",
        "--output",
        bricked.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");
    let before = fs::read_to_string(&bricked).expect("read bricked");

    // `--force`, since running a transform over a file that already carries
    // the other one's work is what this is about.
    let after_path = sandbox.path().join("then-zaa.gcode");
    let output = run(&[
        "--zaa",
        "--force",
        "--output",
        after_path.to_str().unwrap(),
        bricked.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");
    let after = fs::read_to_string(&after_path).expect("read result");
    assert_wellformed(&after);

    assert_eq!(
        heights_of(&before, "Perimeter"),
        heights_of(&after, "Perimeter"),
        "the surface transform moved a bead bricking owns"
    );
    // And it is a run that did something, or the comparison proves nothing.
    let shown = heights_of(&after, "External perimeter");
    assert!(
        shown
            .iter()
            .any(|z| ((z * 5.0).round() / 5.0 - z).abs() > 0.02),
        "the wall that shows still follows the surface"
    );
}

/// A slicer's post-processing field holds a path and nothing else, so a run
/// with no arguments has to do everything. Naming one transform is how you get
/// only that one.
#[test]
fn naming_a_transform_runs_that_one_alone_and_naming_none_runs_both() {
    let sandbox = Sandbox::new("zaa-pick");
    let path = sandbox.with_gcode(&sloped_gcode(6));

    for (name, args, bricked, contoured) in [
        ("both", vec![], true, true),
        ("bricks", vec!["--bricks"], true, false),
        ("zaa", vec!["--zaa"], false, true),
        ("named", vec!["--bricks", "--zaa"], true, true),
    ] {
        let out = sandbox.path().join(format!("{name}.gcode"));
        let mut call = args.clone();
        call.extend(["--output", out.to_str().unwrap(), path.to_str().unwrap()]);
        let output = run(&call);
        assert!(output.status.success(), "{name}: {output:?}");

        let result = fs::read_to_string(&out).expect("read result");
        assert_wellformed(&result);
        assert_eq!(result.contains("corbel brick "), bricked, "{name} bricking");
        assert_eq!(
            result.contains("corbel zaa "),
            contoured,
            "{name} contouring"
        );
    }
}

/// Both at once is the default, and the two must not fight: bricking owns the
/// hidden walls' height and the surface transform owns the rest. Every value
/// that reaches the printer still has to be one it can act on.
#[test]
fn both_transforms_at_once_leave_coherent_gcode() {
    let sandbox = Sandbox::new("zaa-both");
    let path = sandbox.with_gcode(&sloped_gcode(8));
    let out = sandbox.path().join("both.gcode");
    let output = run(&[
        "--verbose",
        "--output",
        out.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");

    let result = fs::read_to_string(&out).expect("read result");
    assert_wellformed(&result);
    assert!(result.contains("corbel brick "));
    assert!(result.contains("corbel zaa "));

    // Nothing below the bed, and nothing further than a layer off its plane.
    for line in result.lines() {
        let body = line.split(';').next().unwrap_or("");
        for word in body.split_whitespace().skip(1) {
            if let Some(digits) = word.strip_prefix('Z') {
                let z: f64 = digits.parse().expect("a number");
                assert!((0.1..=1.7).contains(&z), "commanded {line}");
            }
        }
    }
    // The filament stream never runs backwards.
    let mut spent = 0.0;
    for line in result.lines() {
        let body = line.split(';').next().unwrap_or("").trim();
        if !body.starts_with("G1") && !body.starts_with("G0") {
            continue;
        }
        for word in body.split_whitespace().skip(1) {
            if let Some(digits) = word.strip_prefix('E') {
                let delta: f64 = digits.parse().expect("a number");
                assert!(delta >= 0.0, "backwards: {line}");
                spent += delta;
            }
        }
    }
    assert!(spent > 0.0);

    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("perimeter loops"), "{report}");
    assert!(report.contains("surface moves on"), "{report}");
}

/// Running twice would measure a surface against a plane it is no longer on,
/// so a file carrying either transform's marks is refused rather than
/// processed again.
#[test]
fn a_file_that_has_already_been_contoured_is_refused() {
    let sandbox = Sandbox::new("zaa-again");
    let path = sandbox.with_gcode(&sloped_gcode(6));
    let once = sandbox.path().join("once.gcode");
    assert!(
        run(&[
            "--zaa",
            "--output",
            once.to_str().unwrap(),
            path.to_str().unwrap()
        ])
        .status
        .success()
    );

    let before = fs::read_to_string(&once).expect("read result");
    let output = run(&["--zaa", once.to_str().unwrap()]);
    assert!(!output.status.success());
    let message = String::from_utf8_lossy(&output.stderr);
    assert!(message.contains("has already been contoured"), "{message}");
    assert_eq!(
        fs::read_to_string(&once).expect("read result"),
        before,
        "the file is left alone"
    );

    // And --force is the way through, as it is for bricking.
    assert!(
        run(&["--zaa", "--force", once.to_str().unwrap()])
            .status
            .success()
    );
}

/// How wide a step is worth following is a slope, and a slope is a width over
/// a layer height — so the same file's 3 mm strip is a ramp at 0.2 mm layers
/// and is flat at 0.04 mm ones, where it comes back untouched. Nothing on the
/// command line says so; the file does.
///
/// The shallow height has to clear the fade as well as the reach: everything
/// down to one degree is followed at full amplitude and the quarter past it is
/// where the amplitude tapers away, so 3 mm at 0.05 mm layers is 0.955° and is
/// still carried. At 0.04 mm it is 0.76°, past the taper and left alone.
#[test]
fn how_shallow_a_surface_has_to_be_follows_its_layer_height() {
    let sandbox = Sandbox::new("zaa-slope-angle");

    for (height, followed) in [(0.2, true), (0.04, false)] {
        let path = sandbox.with_gcode(&sloped_gcode_at(6, height));
        let out = sandbox.path().join(format!("reach-{height}.gcode"));
        let output = run(&[
            "--zaa",
            "--output",
            out.to_str().unwrap(),
            path.to_str().unwrap(),
        ]);
        assert!(output.status.success(), "{output:?}");
        let result = fs::read_to_string(&out).expect("read result");
        assert_eq!(
            result.contains("corbel zaa surface"),
            followed,
            "a 3 mm step at {height} mm layers"
        );
        if !followed {
            assert_eq!(result, fs::read_to_string(&path).expect("read input"));
        }
    }
}

/// A part with no shallow surface has nothing to smooth, and has to come back
/// exactly as it arrived rather than with a height command it never asked for.
#[test]
fn a_part_with_nothing_to_smooth_comes_back_untouched() {
    let sandbox = Sandbox::new("zaa-nothing");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);
    let out = sandbox.path().join("zaa.gcode");
    let output = run(&[
        "--zaa",
        "--verbose",
        "--output",
        out.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");
    assert_eq!(fs::read_to_string(&out).expect("read result"), source);

    let report = String::from_utf8_lossy(&output.stderr);
    assert!(report.contains("no surface shallow enough"), "{report}");
}

/// Each transform's settings are grouped under its own heading, so a reader of
/// `--help` can tell which dial belongs to which.
#[test]
fn help_groups_each_transforms_settings_under_its_own_heading() {
    let output = run_bare(&["--help"]);
    assert!(output.status.success(), "{output:?}");
    let help = String::from_utf8_lossy(&output.stdout);

    for heading in ["Bricklayering:", "Z anti-aliasing:"] {
        assert!(help.contains(heading), "{heading} missing from:\n{help}");
    }
    let bricks = help.find("Bricklayering:").expect("a heading");
    let contours = help.find("Z anti-aliasing:").expect("a heading");
    let after = |at: usize, next: usize| &help[at..next];
    assert!(after(bricks, contours).contains("--bricks"), "{help}");
    assert!(after(bricks, contours).contains("--extra-flow"), "{help}");
    assert!(
        help[contours..]
            .lines()
            .any(|line| line.trim_start().starts_with("--zaa ")),
        "{help}"
    );
    // What both share stays above them, where a reader looks first.
    assert!(help[..bricks].contains("--output"), "{help}");
    assert!(help[..bricks].contains("--verbose"), "{help}");
    // And the usage line says up front that one of them has to be named.
    let usage = help.lines().find(|line| line.contains("corbel [OPTIONS]"));
    let usage = usage.expect("a usage line");
    assert!(
        usage.contains("--bricks") && usage.contains("--zaa"),
        "{usage}"
    );
}

/// Naming no transform is refused, with a non-zero exit code, rather than
/// given a default.
///
/// A slicer runs this over the user's only copy of a file and swallows
/// everything it prints, so the one thing it must never do is apply a
/// transform nobody asked for. The failure has to name both switches, since
/// the message is all a reader gets.
#[test]
fn naming_no_transform_fails_instead_of_choosing_one() {
    let sandbox = Sandbox::new("no-transform");
    let source = sample_gcode();
    let path = sandbox.with_gcode(&source);

    let output = run_bare(&[path.to_str().unwrap()]);
    assert!(!output.status.success(), "{output:?}");
    assert_ne!(output.status.code(), Some(0));

    let complaint = String::from_utf8_lossy(&output.stderr);
    assert!(complaint.contains("--bricks"), "{complaint}");
    assert!(complaint.contains("--zaa"), "{complaint}");

    // And the file it was pointed at is exactly as it was.
    assert_eq!(fs::read_to_string(&path).expect("read input"), source);
}

/// Each switch runs its own transform and only its own, and the two together
/// run both. What each writes is stamped, so which ran is read off the file
/// rather than off the report.
#[test]
fn each_switch_selects_exactly_its_own_transform() {
    let sandbox = Sandbox::new("select");
    let source = sloped_gcode(14);
    let path = sandbox.with_gcode(&source);

    for (args, bricked, contoured) in [
        (vec!["--bricks"], true, false),
        (vec!["--zaa"], false, true),
        (vec!["--bricks", "--zaa"], true, true),
    ] {
        let out = sandbox.path().join(format!("{}.gcode", args.join("")));
        let mut all = args.clone();
        all.extend(["--output", out.to_str().unwrap(), path.to_str().unwrap()]);
        let output = run_bare(&all);
        assert!(output.status.success(), "{args:?}: {output:?}");

        let result = fs::read_to_string(&out).expect("read result");
        assert_eq!(
            result.contains("corbel brick "),
            bricked,
            "{args:?} should{} brick",
            if bricked { "" } else { " not" }
        );
        assert_eq!(
            result.contains("corbel zaa "),
            contoured,
            "{args:?} should{} contour",
            if contoured { "" } else { " not" }
        );
    }
}

/// PrusaSlicer 2.8.1 binary G-code, the same fixture the container tests use.
const BINARY_SINGLE: &[u8] = include_bytes!("fixtures/mini_cube_ps2.8.1.bgcode");
/// PrusaSlicer 2.6.0 binary G-code, ten G-code blocks.
const BINARY_MULTI: &[u8] = include_bytes!("fixtures/mini_cube_b.bgcode");

/// The head of a 3MF, which is a zip: the local file header, then a deflated
/// member. Anything a mistyped path lands on looks like this rather than like
/// G-code, and the zero bytes in the header are the giveaway.
const THREE_MF: &[u8] = b"PK\x03\x04\x14\x00\x00\x00\x08\x00\x00\x00!\x00\
    \x9b\xc7\x1d\x8b\x1c\x02\x00\x00\x8b\x05\x00\x00\x13\x00\x00\x00\
    [Content_Types].xml\xad\x94\xcbn\xdb0\x10E\xf7\x05\xfa\x07A\xbb";

/// An ASCII STL: no zero byte anywhere, and not one line that reads as a
/// command or a comment.
const ASCII_STL: &str = "solid cube\n\
     facet normal 0 0 -1\n\
     outer loop\n\
     vertex 0 0 0\n\
     vertex 20 20 0\n\
     vertex 20 0 0\n\
     endloop\n\
     endfacet\n\
     endsolid cube\n";

/// A file that is not G-code is refused with the original left byte for byte
/// as it was.
///
/// The default output target is the input itself and a slicer hands over the
/// only copy it has, so a mistyped path onto a model would otherwise come back
/// rewritten past recovery — every byte that is not UTF-8 replaced, every
/// terminator changed — and exit zero while doing it.
#[test]
fn a_file_that_is_not_gcode_is_refused_and_left_byte_identical() {
    let sandbox = Sandbox::new("not-gcode");

    for (name, source) in [
        ("model.3mf", THREE_MF),
        ("model.stl", ASCII_STL.as_bytes()),
        ("empty.gcode", b"".as_slice()),
    ] {
        let path = sandbox.with_named(name, source);
        let output = run(&[path.to_str().unwrap()]);

        assert!(!output.status.success(), "{name} was accepted: {output:?}");
        let complaint = String::from_utf8_lossy(&output.stderr);
        assert!(complaint.contains(name), "{name}: {complaint}");
        assert!(
            complaint.contains("does not read as G-code"),
            "{name}: {complaint}"
        );
        assert_eq!(
            fs::read(&path).expect("read the input back"),
            source,
            "{name} was rewritten by a refused run"
        );
    }

    // The refusal lands before a sink is ever opened, so not even a temporary
    // appears beside the file.
    let mut left: Vec<String> = fs::read_dir(sandbox.path())
        .unwrap()
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.file_name().to_string_lossy().into_owned())
        .collect();
    left.sort();
    assert_eq!(left, ["empty.gcode", "model.3mf", "model.stl"]);
}

/// `--force` already means "I know what I am doing" for a file that carries an
/// earlier run's marks, and it is the only thing that overrides the refusal.
#[test]
fn force_processes_a_file_that_does_not_read_as_gcode() {
    let sandbox = Sandbox::new("force-not-gcode");
    let path = sandbox.with_named("model.stl", ASCII_STL.as_bytes());
    let target = sandbox.path().join("out.gcode");

    let output = run(&[
        "--bricks",
        "--force",
        "-o",
        target.to_str().unwrap(),
        path.to_str().unwrap(),
    ]);
    assert!(output.status.success(), "{output:?}");
    let result = fs::read_to_string(&target).expect("read the result");
    assert!(
        result.contains("endsolid cube"),
        "--force must process it rather than refuse it: {result}"
    );
}

/// The refusal must not reach a real file, whichever container it arrived in.
/// A binary container is binary on disk and G-code once decoded, so it is the
/// decoded stream that has to be judged.
#[test]
fn gcode_is_still_accepted_however_it_is_packed() {
    let sandbox = Sandbox::new("still-gcode");

    let plain = sandbox.with_gcode(&sample_gcode());
    let output = run(&[plain.to_str().unwrap()]);
    assert!(output.status.success(), "{output:?}");

    for (name, fixture) in [
        ("single.bgcode", BINARY_SINGLE),
        ("multi.bgcode", BINARY_MULTI),
    ] {
        let path = sandbox.with_named(name, fixture);
        let output = run(&["--verbose", path.to_str().unwrap()]);
        let report = String::from_utf8_lossy(&output.stderr);
        assert!(
            !report.contains("does not read as G-code"),
            "{name} was judged on its container rather than on its G-code: {report}"
        );
    }
}
