//! Throughput of the passes over a synthetic slice, so a change that costs
//! time shows up before it reaches a print.
//!
//! Deliberately without a benchmark framework: the work here is measured in
//! hundreds of milliseconds over millions of lines, which a wall clock resolves
//! perfectly well and which no sampling harness would make more honest.
//!
//! Run with `cargo bench`. Numbers are only comparable within one machine and
//! one run, so change one thing and re-run both sides.

use std::hint::black_box;
use std::io;
use std::time::{Duration, Instant};

use corbel::brick;
use corbel::scan::Survey;
use corbel::zaa;

/// Layers of the synthetic part. Enough that per-layer work is not lost in the
/// start G-code, few enough that a run stays under a second.
const LAYERS: usize = 300;

/// Loops per wall, which is what `brick` alternates between.
const LOOPS: usize = 4;

/// Segments per loop. Real slices emit moves around a millimetre long, so a
/// synthetic file with longer ones would measure geometry no print produces.
const SEGMENTS: usize = 120;

/// How far the part narrows each layer, in mm. It gives the top of every layer
/// a strip of itself exposed — the staircase `zaa` follows — rather than a
/// vertical wall it would have nothing to do with.
const TAPER: f64 = 0.06;

fn main() {
    let source = slice();
    let lines = source.lines().count();
    println!(
        "input: {:.1} MB, {lines} lines, {LAYERS} layers\n",
        source.len() as f64 / 1e6
    );

    let survey = Survey::of(&source);
    report("survey", &source, || {
        black_box(Survey::read(source.as_bytes()).expect("reading a slice cannot fail"));
    });
    report("brick", &source, || {
        let stats = brick::stream(
            source.as_bytes(),
            io::sink(),
            &brick::Config::default(),
            &survey,
        )
        .expect("writing to a sink cannot fail");
        black_box(stats);
    });
    report("zaa", &source, || {
        let stats = zaa::stream(
            source.as_bytes(),
            source.as_bytes(),
            io::sink(),
            &zaa::Config::default(),
            &survey,
        )
        .expect("writing to a sink cannot fail");
        black_box(stats);
    });
    report("both", &source, || {
        let mut pass = zaa::Pass::new(
            io::sink(),
            source.as_bytes(),
            &zaa::Config::default(),
            &survey,
        );
        let bricked = brick::stream(
            source.as_bytes(),
            &mut pass,
            &brick::Config::default(),
            &survey,
        )
        .expect("writing to a sink cannot fail");
        black_box((bricked, pass.finish().expect("finishing cannot fail")));
    });
}

/// Runs `work` a few times and reports the fastest, which is the one least
/// disturbed by whatever else the machine was doing.
fn report(name: &str, source: &str, mut work: impl FnMut()) {
    const RUNS: usize = 5;

    let mut best = Duration::MAX;
    for _ in 0..RUNS {
        let start = Instant::now();
        work();
        best = best.min(start.elapsed());
    }
    println!(
        "{name:>7}: {:>7.1} ms   {:>6.0} MB/s",
        best.as_secs_f64() * 1e3,
        source.len() as f64 / 1e6 / best.as_secs_f64()
    );
}

/// A slice shaped like the ones slicers emit: layer markers, region markers,
/// concentric wall loops printed innermost first, and sparse infill between
/// them, with a solid surface at each end.
fn slice() -> String {
    let mut text = String::with_capacity(64 << 20);
    text.push_str("; generated by corbel benchmark\n; layer_height = 0.2\n");
    text.push_str("; first_layer_height = 0.2\nM83\nG21\nG90\nG92 E0\n");

    for layer in 0..LAYERS {
        let z = 0.2 + layer as f64 * 0.2;
        let narrow = TAPER * layer as f64;
        text.push_str(";LAYER_CHANGE\n");
        text.push_str(&format!("G1 Z{z:.3} F600\n"));

        if layer == 0 || layer + 1 == LAYERS {
            text.push_str(";TYPE:Solid infill\n");
            fill(&mut text, 0.0);
            continue;
        }

        text.push_str(";TYPE:Perimeter\n");
        for index in 0..LOOPS {
            wall(&mut text, narrow + 0.45 * (LOOPS - 1 - index) as f64);
        }
        text.push_str(";TYPE:External perimeter\n");
        wall(&mut text, narrow - 0.45);
        text.push_str(";TYPE:Top solid infill\n");
        wall(&mut text, narrow + 0.45 * LOOPS as f64);
        text.push_str(";TYPE:Internal infill\n");
        fill(&mut text, 3.0);
    }
    text.push_str("M107\nM104 S0\n");
    text
}

/// One closed loop inset by `inset`, walked in millimetre steps.
fn wall(text: &mut String, inset: f64) {
    let radius = 30.0 - inset;
    text.push_str(&format!("G1 X{radius:.3} Y0.000 F9000\n"));
    for step in 1..=SEGMENTS {
        let angle = std::f64::consts::TAU * step as f64 / SEGMENTS as f64;
        let (x, y) = (radius * angle.cos(), radius * angle.sin());
        text.push_str(&format!("G1 X{x:.3} Y{y:.3} E0.04521\n"));
    }
}

/// A raster of short extrusions, standing in for infill.
fn fill(text: &mut String, gap: f64) {
    let rows = if gap > 0.0 { 12 } else { 40 };
    for row in 0..rows {
        let y = -20.0 + row as f64 * 40.0 / rows as f64;
        text.push_str(&format!("G1 X-20.000 Y{y:.3} F9000\n"));
        for step in 1..=40 {
            let x = -20.0 + step as f64;
            text.push_str(&format!("G1 X{x:.3} Y{y:.3} E0.03310\n"));
        }
    }
}
