//! Post-processes sliced G-code with two independent transforms.
//!
//! [`brick`] raises every other internal perimeter loop by half a layer
//! height, staggering the seams between loops so that layers interlock instead
//! of stacking as independent flat sheets — which is where FDM prints are
//! weakest — and draws the visible wall a few microns toward the material
//! behind it so the joint against it closes without the part growing.
//!
//! [`zaa`] follows the model's surface *within* a layer, varying the height of
//! an extrusion by up to half a layer either way so that a shallow top comes
//! out as a ramp rather than a staircase.
//!
//! Either, or both: they own different regions of the print, so composing them
//! costs one pass over the file rather than two.
//!
//! It streams: G-code arrives a line at a time from a [`Source`] and leaves a
//! line at a time through a [`Sink`], so a file is never held in memory.

pub mod bgcode;
pub mod brick;
mod error;
pub mod gcode;
pub mod geometry;
pub mod scan;
pub mod slicer;
pub mod zaa;

pub use error::{Error, Result};

use std::fs::{self, File};
use std::io::{self, BufRead, BufReader, BufWriter, Read, Seek, Write};
use std::path::{Path, PathBuf};
use std::time::SystemTime;

use crate::scan::Survey;

/// Bytes buffered before touching the disk. The transform writes one short line
/// at a time, so this is what keeps that from becoming one syscall per line.
const WRITE_BUFFER: usize = 256 * 1024;

/// How much of the decoded head is examined to decide the input is G-code at
/// all. Every slicer this tool reads opens its file on a comment — Prusa's
/// `; generated by`, Cura's `;FLAVOR:`, Orca's `; HEADER_BLOCK_START` — and a
/// hand-written file opens on a command, so the evidence arrives in the first
/// line and four kilobytes is thousands of lines of slack. It is a fixed
/// budget rather than a share of the file, so a run's peak memory still does
/// not depend on the file's size.
const SNIFF: usize = 4 * 1024;

/// How many names a temporary is allowed to try before giving up. A name is
/// unpredictable, so a collision means another `corbel` drew the same 64 bits
/// in the same directory; one retry is already generous.
const ATTEMPTS: usize = 8;

/// A G-code file: where to read it from, and which container a rewrite has to
/// go back into.
///
/// The transform needs a [`Survey`] of the whole file before it can rewrite any
/// of it, so the input is read twice and never held in memory. A binary
/// container costs one walk over its block headers when it is opened, which is
/// what a rewrite has to put back around the G-code; its blocks are then
/// unpacked one at a time on each pass.
#[derive(Clone, Debug)]
pub struct Source {
    path: PathBuf,
    kind: Kind,
    endings: Endings,
}

#[derive(Clone, Debug)]
enum Kind {
    Text,
    Binary { container: bgcode::Container },
}

impl Source {
    /// Opens `path`, refusing anything that does not read as G-code.
    ///
    /// A slicer hands a post-processor the one copy of its file and swallows
    /// whatever the script prints, so a mistyped path onto a `.3mf`, an STL or
    /// any other binary is a print nobody can get back: the default output
    /// target is the input itself, and pass-through runs every byte through a
    /// lossy UTF-8 repair on its way out. Same reasoning as refusing a run that
    /// names no transform — what this tool does to a file is not something to
    /// guess at on the user's behalf.
    pub fn open(path: &Path) -> Result<Self> {
        let (source, head) = Self::sniffed(path)?;
        if let Some(saw) = unlike_gcode(&head) {
            return Err(Error::NotGcode {
                path: source.path,
                saw,
            });
        }
        Ok(source)
    }

    /// Opens `path` without asking whether it is G-code, which is what
    /// `--force` means.
    pub fn open_forced(path: &Path) -> Result<Self> {
        Ok(Self::sniffed(path)?.0)
    }

    /// Opens `path` and reads the head of the G-code it decodes to.
    ///
    /// That head answers two questions at once: whether this is G-code at all,
    /// and which line ending it arrived with. Both are read through
    /// [`Source::reader`], so a binary container is judged on the G-code it
    /// unpacks to rather than on the bytes it is packed as, and the budget is
    /// fixed so a run's peak memory still does not follow the file's size.
    fn sniffed(path: &Path) -> Result<(Self, Vec<u8>)> {
        let mut source = Self::container(path)?;
        let mut head = vec![0u8; SNIFF];
        let read = fill(&mut source.reader()?, &mut head).map_err(|s| Error::io(path, s))?;
        head.truncate(read);
        source.endings = source.endings_of(&head)?;
        Ok((source, head))
    }

    /// Which container the file is in, before anything is read out of it.
    fn container(path: &Path) -> Result<Self> {
        let mut file = File::open(path).map_err(|source| Error::io(path, source))?;
        let mut magic = [0u8; 4];
        let read = fill(&mut file, &mut magic).map_err(|source| Error::io(path, source))?;

        let path = path.to_path_buf();
        if !bgcode::is_binary(&magic[..read]) {
            return Ok(Self {
                path,
                kind: Kind::Text,
                endings: Endings::default(),
            });
        }

        let container = bgcode::Container::read(BufReader::with_capacity(WRITE_BUFFER, file))
            .map_err(|reason| Error::Bgcode {
                path: path.clone(),
                reason,
            })?;

        Ok(Self {
            path,
            kind: Kind::Binary { container },
            endings: Endings::default(),
        })
    }

    /// The line ending this file arrived with, and whether its last line
    /// carried one.
    ///
    /// Every reader here strips a trailing `\r` and every writer emits a bare
    /// `\n`, so without this a file authored on Windows comes back with every
    /// line changed even where neither transform touched it. It is read off
    /// the head that has already been fetched plus, at most, the file's last
    /// byte — never a second pass, and never the file in memory.
    fn endings_of(&self, head: &[u8]) -> Result<Endings> {
        let carriage_return = match head.iter().position(|byte| *byte == b'\n') {
            Some(0) | None => false,
            Some(at) => head[at - 1] == b'\r',
        };
        Ok(Endings {
            carriage_return,
            final_newline: self.ends_on_a_newline(head)?,
        })
    }

    fn ends_on_a_newline(&self, head: &[u8]) -> Result<bool> {
        if head.len() < SNIFF {
            // `fill` only stops short of its buffer at the end of the stream,
            // so the head is the whole file and its last byte is in hand.
            return Ok(head.last().is_none_or(|byte| *byte == b'\n'));
        }
        if self.is_binary() {
            // The G-code is packed in blocks, so its last byte costs a whole
            // decode to reach. One newline is not worth a third pass.
            return Ok(true);
        }
        let mut file = File::open(&self.path).map_err(|s| Error::io(&self.path, s))?;
        file.seek(io::SeekFrom::End(-1))
            .map_err(|s| Error::io(&self.path, s))?;
        let mut last = [0u8; 1];
        let read = fill(&mut file, &mut last).map_err(|s| Error::io(&self.path, s))?;
        Ok(read == 0 || last[0] == b'\n')
    }

    pub fn path(&self) -> &Path {
        &self.path
    }

    pub fn is_binary(&self) -> bool {
        matches!(self.kind, Kind::Binary { .. })
    }

    /// Layer height the file states about itself. Plain G-code carries it as a
    /// comment the survey already sees; binary G-code keeps it in a metadata
    /// block, outside the G-code stream.
    pub fn layer_height(&self) -> Option<f64> {
        match &self.kind {
            Kind::Text => None,
            Kind::Binary { container, .. } => container.layer_height,
        }
    }

    /// Width the internal perimeters were metered at, for the same reason.
    pub fn wall_width(&self) -> Option<f64> {
        match &self.kind {
            Kind::Text => None,
            Kind::Binary { container, .. } => container.wall_width,
        }
    }

    /// Nozzle diameter the file states about itself, for the same reason.
    pub fn nozzle(&self) -> Option<f64> {
        match &self.kind {
            Kind::Text => None,
            Kind::Binary { container, .. } => container.nozzle,
        }
    }

    /// A reader positioned at the start. Each call is an independent pass.
    pub fn reader(&self) -> Result<Reader> {
        let file = File::open(&self.path).map_err(|s| Error::io(&self.path, s))?;
        let input = BufReader::with_capacity(WRITE_BUFFER, file);

        Ok(Reader(match &self.kind {
            Kind::Text => Stream::File(input),
            Kind::Binary { container } => {
                Stream::Blocks(container.blocks(input).map_err(|reason| Error::Bgcode {
                    path: self.path.clone(),
                    reason,
                })?)
            }
        }))
    }

    pub fn survey(&self) -> Result<Survey> {
        Survey::read(self.reader()?).map_err(|source| Error::io(&self.path, source))
    }

    /// A destination that will replace `target` with this file's container
    /// format once the rewrite is complete.
    ///
    /// `target` is resolved through any symbolic link first, so what is
    /// replaced is the file the user actually keeps rather than the link
    /// standing in for it.
    pub fn sink(&self, target: &Path) -> Result<Sink> {
        let target = destination(target);
        let mode = intended_mode([target.as_path(), self.path.as_path()]);
        // Named for the target, since that is the path the caller asked for
        // and the temporary beside it is this module's business.
        let (file, temporary) =
            create_temporary(&target, mode).map_err(|source| Error::io(&target, source))?;
        let warnings = losses(&target, &file);

        let writer = match &self.kind {
            Kind::Text => Writer::Text(BufWriter::with_capacity(WRITE_BUFFER, file)),
            Kind::Binary { container, .. } => Writer::Binary(
                container
                    .writer(file)
                    .map_err(|source| Error::io(&temporary, source))?,
            ),
        };

        Ok(Sink {
            writer: Some(writer),
            endings: self.endings,
            held: false,
            temporary,
            target,
            committed: false,
            warnings,
        })
    }

    /// Streams this source through `transform` and commits the result.
    ///
    /// The reader is closed before the sink replaces its target, so rewriting a
    /// file in place never renames over a handle that is still open.
    pub fn rewrite<T>(
        &self,
        mut sink: Sink,
        transform: impl FnOnce(Reader, &mut Sink) -> io::Result<T>,
    ) -> Result<T> {
        let outcome = {
            let reader = self.reader()?;
            transform(reader, &mut sink).map_err(|source| Error::io(&self.path, source))?
        };
        sink.commit()?;
        Ok(outcome)
    }
}

/// One pass over a [`Source`].
pub struct Reader(Stream);

enum Stream {
    File(BufReader<File>),
    Blocks(bgcode::BlockReader<BufReader<File>>),
}

impl Read for Reader {
    fn read(&mut self, buffer: &mut [u8]) -> io::Result<usize> {
        match &mut self.0 {
            Stream::File(reader) => reader.read(buffer),
            Stream::Blocks(reader) => reader.read(buffer),
        }
    }
}

impl BufRead for Reader {
    fn fill_buf(&mut self) -> io::Result<&[u8]> {
        match &mut self.0 {
            Stream::File(reader) => reader.fill_buf(),
            Stream::Blocks(reader) => reader.fill_buf(),
        }
    }

    fn consume(&mut self, amount: usize) {
        match &mut self.0 {
            Stream::File(reader) => reader.consume(amount),
            Stream::Blocks(reader) => reader.consume(amount),
        }
    }
}

/// A write destination that only replaces its target once the rewrite is
/// complete.
///
/// Slicers hand a post-processor the one copy of the G-code they have, so a
/// crash partway through must leave the original untouched. Everything goes to
/// a temporary file beside the target, which is renamed over it at the end and
/// deleted if the rewrite never gets there.
///
/// It also puts back the line ending the input arrived with: the readers strip
/// `\r` and the transforms write `\n`, so this is the one place that knows what
/// the file looked like.
pub struct Sink {
    writer: Option<Writer>,
    endings: Endings,
    /// A newline held back because it may turn out to be the file's last byte,
    /// on a file that did not end on one.
    held: bool,
    temporary: PathBuf,
    target: PathBuf,
    committed: bool,
    warnings: Vec<String>,
}

/// How the input's lines ended, which is how the output's have to.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct Endings {
    carriage_return: bool,
    final_newline: bool,
}

impl Default for Endings {
    /// What a file with no line ending in it at all is written as, and the
    /// shape every mainstream slicer emits.
    fn default() -> Self {
        Self {
            carriage_return: false,
            final_newline: true,
        }
    }
}

impl Endings {
    /// Whether the bytes a transform writes are already the bytes the file
    /// wants, which is the common case and has to cost nothing.
    fn verbatim(self) -> bool {
        !self.carriage_return && self.final_newline
    }
}

enum Writer {
    Text(BufWriter<File>),
    Binary(bgcode::BlockWriter<File>),
}

impl Sink {
    /// Finishes the file and moves it over the target.
    pub fn commit(mut self) -> Result<()> {
        // A newline still held here is the one the input did not carry, so it
        // is dropped rather than written.
        let writer = self.writer.take().expect("a sink is committed once");
        writer
            .finish()
            .map_err(|source| Error::io(&self.temporary, source))?;
        fs::rename(&self.temporary, &self.target)
            .map_err(|source| Error::io(&self.target, source))?;
        self.committed = true;
        Ok(())
    }

    /// What replacing the target costs that this tool cannot carry over, for
    /// the caller to say out loud. Empty on the ordinary run.
    pub fn warnings(&self) -> &[String] {
        &self.warnings
    }

    fn writer(&mut self) -> &mut Writer {
        self.writer.as_mut().expect("a sink is committed once")
    }

    /// Writes `data` with the input's own line endings put back.
    fn restore(&mut self, mut data: &[u8]) -> io::Result<()> {
        if data.is_empty() {
            return Ok(());
        }
        if self.held {
            // More arrived, so the newline held back was not the last byte.
            self.held = false;
            self.newline()?;
        }
        if !self.endings.final_newline && data.last() == Some(&b'\n') {
            self.held = true;
            data = &data[..data.len() - 1];
        }
        if !self.endings.carriage_return {
            return self.writer().write_all(data);
        }
        while let Some(at) = data.iter().position(|byte| *byte == b'\n') {
            self.writer().write_all(&data[..at])?;
            self.newline()?;
            data = &data[at + 1..];
        }
        self.writer().write_all(data)
    }

    fn newline(&mut self) -> io::Result<()> {
        let ending: &[u8] = if self.endings.carriage_return {
            b"\r\n"
        } else {
            b"\n"
        };
        self.writer().write_all(ending)
    }
}

impl Write for Sink {
    fn write(&mut self, data: &[u8]) -> io::Result<usize> {
        if self.endings.verbatim() {
            return self.writer().write(data);
        }
        self.restore(data)?;
        Ok(data.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        // A held newline is deliberately not flushed: it is only written once
        // something proves it was not the file's last byte.
        self.writer().flush()
    }
}

impl Drop for Sink {
    fn drop(&mut self) {
        if !self.committed {
            drop(self.writer.take());
            let _ = fs::remove_file(&self.temporary);
        }
    }
}

impl Writer {
    fn finish(self) -> io::Result<()> {
        let file = match self {
            Writer::Text(out) => out.into_inner().map_err(io::IntoInnerError::into_error)?,
            Writer::Binary(out) => out.finish()?,
        };
        // The rename that follows is only atomic if the bytes reached the disk
        // first. Without this a power cut can leave the target's name pointing
        // at a file whose contents were never written.
        file.sync_all()
    }
}

impl Write for Writer {
    fn write(&mut self, data: &[u8]) -> io::Result<usize> {
        match self {
            Writer::Text(out) => out.write(data),
            Writer::Binary(out) => out.write(data),
        }
    }

    fn flush(&mut self) -> io::Result<()> {
        match self {
            Writer::Text(out) => out.flush(),
            Writer::Binary(out) => out.flush(),
        }
    }
}

/// Beside the target, so the final rename cannot cross a filesystem, and under
/// a name no other process can work out in advance.
///
/// A slicer runs its post-processing script over a file in the system temp
/// directory, which every local user may write to. A name built from the
/// target and the process id is one another user can create ahead of us — as a
/// symlink onto a file of their choosing — so the token is what turns guessing
/// it into a guess rather than a countdown.
fn temporary_path(target: &Path) -> PathBuf {
    let mut name = target.file_name().unwrap_or_default().to_os_string();
    name.push(format!(".{}.{:016x}.tmp", std::process::id(), token()));
    target.with_file_name(name)
}

/// A number another process cannot predict.
///
/// `RandomState` is seeded from the operating system's randomness and stirred
/// on every call, which is what the process id and the clock underneath it are
/// not: both are guessable, and both repeat across machines.
fn token() -> u64 {
    use std::collections::hash_map::RandomState;
    use std::hash::{BuildHasher, Hasher};

    let mut hasher = RandomState::new().build_hasher();
    hasher.write_u32(std::process::id());
    if let Ok(since) = SystemTime::now().duration_since(SystemTime::UNIX_EPOCH) {
        hasher.write_u128(since.as_nanos());
    }
    hasher.finish()
}

/// Creates the temporary, refusing to open anything that is already there.
///
/// `create_new` is `O_EXCL`, which fails on an existing name of any kind — a
/// symlink included, and without following it — so a name another user got to
/// first is an error here rather than their file being truncated and filled
/// with someone else's print.
fn create_temporary(target: &Path, mode: u32) -> io::Result<(File, PathBuf)> {
    let mut taken = None;
    for _ in 0..ATTEMPTS {
        let path = temporary_path(target);
        match create_exclusively(&path, mode) {
            Ok(file) => {
                // `open` masks the mode with the umask, so the file can only
                // have been created narrower than asked for, never wider.
                // Opening it back up to the target's own permissions happens
                // before a byte is written, so there is no window in which
                // anyone may read what they could not read before.
                set_mode(&file, mode);
                return Ok((file, path));
            }
            Err(error) if error.kind() == io::ErrorKind::AlreadyExists => taken = Some(error),
            Err(error) => return Err(error),
        }
    }
    Err(taken.unwrap_or_else(|| {
        io::Error::new(
            io::ErrorKind::AlreadyExists,
            "no free name for a temporary file beside the target",
        )
    }))
}

/// The file a rewrite has to replace, with every symbolic link on the way to
/// it followed.
///
/// `rename` replaces the link itself, not what it points at, so writing to the
/// path as given leaves the real file holding the unprocessed G-code and the
/// link gone. A slicer's output directory pointed at shared storage hits that
/// on every run. Resolving the directory too keeps the temporary beside the
/// file it will replace, which is what keeps the rename on one filesystem.
fn destination(target: &Path) -> PathBuf {
    let mut at = target.to_path_buf();
    for _ in 0..LINKS {
        let Ok(metadata) = fs::symlink_metadata(&at) else {
            break;
        };
        if !metadata.file_type().is_symlink() {
            break;
        }
        let Ok(to) = fs::read_link(&at) else {
            break;
        };
        at = match at.parent() {
            Some(directory) if to.is_relative() => directory.join(to),
            _ => to,
        };
    }
    let real = at
        .parent()
        .filter(|directory| !directory.as_os_str().is_empty())
        .and_then(|directory| fs::canonicalize(directory).ok())
        .zip(at.file_name())
        .map(|(directory, name)| directory.join(name));
    real.unwrap_or(at)
}

/// How many links deep a target may be before this gives up and writes where
/// it has got to. The kernel's own limit on a path is the same order.
const LINKS: usize = 16;

/// The permissions the replacement has to end up with: the target's if it is
/// there, else the input's, and failing both nothing wider than its owner.
/// A G-code file the user kept private stays private; the set-user-ID bits are
/// never copied.
#[cfg(unix)]
fn intended_mode<const N: usize>(models: [&Path; N]) -> u32 {
    use std::os::unix::fs::PermissionsExt;

    models
        .iter()
        .find_map(|path| fs::metadata(path).ok())
        .map_or(0o600, |metadata| metadata.permissions().mode() & 0o777)
}

/// Windows permissions carry only a read-only flag, and copying that onto a
/// file still being written would block the rename that follows.
#[cfg(not(unix))]
fn intended_mode<const N: usize>(_: [&Path; N]) -> u32 {
    0
}

#[cfg(unix)]
fn create_exclusively(path: &Path, mode: u32) -> io::Result<File> {
    use std::os::unix::fs::OpenOptionsExt;

    fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(mode)
        .open(path)
}

#[cfg(not(unix))]
fn create_exclusively(path: &Path, _: u32) -> io::Result<File> {
    fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
}

#[cfg(unix)]
fn set_mode(file: &File, mode: u32) {
    use std::os::unix::fs::PermissionsExt;

    let _ = file.set_permissions(fs::Permissions::from_mode(mode));
}

#[cfg(not(unix))]
fn set_mode(_: &File, _: u32) {}

/// What replacing `target` with a fresh file leaves behind.
///
/// A rename publishes a NEW inode, so everything the old one carried outside
/// its mode bits goes with it: the owner, any POSIX ACL, any SELinux or
/// AppArmor label, and every other name hard-linked to it. `std` has no
/// `chown` and no way to read an extended attribute, and this project does not
/// take a dependency for it, so what can be detected is said out loud rather
/// than changed in silence. A run under `sudo`, or from a print-server daemon,
/// is the case that matters: it leaves the user's own G-code owned by root
/// with mode bits that still say `rw-------`.
#[cfg(unix)]
fn losses(target: &Path, temporary: &File) -> Vec<String> {
    use std::os::unix::fs::MetadataExt;

    let mut warnings = Vec::new();
    let (Ok(replaced), Ok(replacement)) = (fs::metadata(target), temporary.metadata()) else {
        return warnings;
    };
    if (replaced.uid(), replaced.gid()) != (replacement.uid(), replacement.gid()) {
        warnings.push(format!(
            "{} belongs to {}:{}, and the file replacing it will belong to \
             {}:{} — run corbel as the owner if the print has to stay theirs",
            target.display(),
            replaced.uid(),
            replaced.gid(),
            replacement.uid(),
            replacement.gid(),
        ));
    }
    if replaced.nlink() > 1 {
        warnings.push(format!(
            "{} has {} other name(s) hard-linked to it, and only this one is \
             replaced; the others keep the file as it was sliced",
            target.display(),
            replaced.nlink() - 1,
        ));
    }
    warnings
}

#[cfg(not(unix))]
fn losses(_: &Path, _: &File) -> Vec<String> {
    Vec::new()
}

/// What the head of a file looks like if it does not look like G-code, or
/// `None` if it does.
fn unlike_gcode(head: &[u8]) -> Option<String> {
    if let Some(at) = head.iter().position(|byte| *byte == 0) {
        return Some(format!("a zero byte {at} bytes in"));
    }
    let mut lines = gcode::Lines::new(io::Cursor::new(head));
    // Reading from a slice in memory cannot fail, so an error here is the end
    // of the head and the evidence has not arrived.
    while let Ok(Some(line)) = lines.next_line() {
        if reads_as_gcode(line.text) {
            return None;
        }
    }
    Some(if head.is_empty() {
        "an empty file".into()
    } else {
        format!("no command or comment in its first {} bytes", head.len())
    })
}

/// Whether one line is evidence that a stream is G-code.
///
/// A whole-line comment or a command this tool acts on is decisive on its own.
/// Everything else a slicer writes reaches [`gcode::Code::Other`] — `G28`,
/// `M104`, `T0` — so a bare command word counts too: a letter and a number,
/// which is the shape every dialect shares and which `Code` does not name only
/// because neither transform has to act on it.
fn reads_as_gcode(raw: &str) -> bool {
    let line = gcode::Line::parse(raw);
    if line.marker().is_some() || line.code != gcode::Code::Other {
        return true;
    }
    let mut word = raw.trim_start().bytes();
    word.next().is_some_and(|byte| byte.is_ascii_alphabetic())
        && word.next().is_some_and(|byte| byte.is_ascii_digit())
}

/// Reads until `buffer` is full or the stream ends, returning how much arrived.
fn fill(reader: &mut impl Read, buffer: &mut [u8]) -> io::Result<usize> {
    let mut read = 0;
    while read < buffer.len() {
        match reader.read(&mut buffer[read..]) {
            Ok(0) => break,
            Ok(count) => read += count,
            Err(error) if error.kind() == io::ErrorKind::Interrupted => {}
            Err(error) => return Err(error),
        }
    }
    Ok(read)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A directory of this run's own, since the tests share a process.
    fn scratch(name: &str) -> PathBuf {
        let path = std::env::temp_dir().join(format!("corbel-{}-{name}", std::process::id()));
        let _ = fs::remove_dir_all(&path);
        fs::create_dir_all(&path).expect("a writable temp directory");
        path
    }

    /// What [`Source::open`] made of a file with these contents.
    fn opened(name: &str, contents: &[u8]) -> Result<Source> {
        let path = scratch(name).join("input");
        fs::write(&path, contents).expect("seed the input");
        Source::open(&path)
    }

    /// The evidence a line carries, one shape at a time. A slicer's own
    /// preamble is comments; a start G-code is commands, most of which this
    /// tool never acts on and so reads as `Code::Other`.
    #[test]
    fn a_line_reads_as_gcode_when_it_is_a_command_or_a_comment() {
        for line in [
            "; generated by PrusaSlicer 2.8.1",
            ";FLAVOR:Marlin",
            ";TYPE:Perimeter",
            "G1 X20.000 Y0.000 E0.66000",
            "M83",
            "G28 ; home",
            "M104 S210",
            "T0",
            "N7 G1 X1",
        ] {
            assert!(reads_as_gcode(line), "{line}");
        }

        // An ASCII STL and a Wavefront OBJ, which are what a mistyped path
        // most often lands on that has no zero byte to give it away.
        for line in [
            "solid cube",
            "facet normal 0 0 -1",
            "vertex 0 0 0",
            "endsolid cube",
            "v 0.0 1.0 2.0",
            "# a comment in some other language",
            "",
        ] {
            assert!(!reads_as_gcode(line), "{line}");
        }
    }

    /// A slicer hands over the only copy of a file it has, and the default
    /// output target is that file, so anything unrecognisable stops the run
    /// before a sink is ever opened.
    #[test]
    fn a_file_that_is_not_gcode_is_refused_by_name() {
        let zipped = b"PK\x03\x04\x14\x00\x00\x00\x08\x00 a 3mf is a zip";
        let Err(error) = opened("zip", zipped) else {
            panic!("a zip was taken for G-code");
        };
        assert!(error.to_string().contains("zero byte"), "{error}");

        let Err(error) = opened("stl", b"solid cube\nvertex 0 0 0\nendsolid cube\n") else {
            panic!("an ASCII STL was taken for G-code");
        };
        assert!(
            error.to_string().contains("no command or comment"),
            "{error}"
        );

        let Err(error) = opened("empty", b"") else {
            panic!("an empty file was taken for G-code");
        };
        assert!(error.to_string().contains("empty"), "{error}");
    }

    /// The evidence only has to arrive once, and a slicer's file opens with
    /// it. A comment carrying bytes that are not UTF-8 still counts: slicers
    /// copy object names in the host's encoding, and refusing those would
    /// refuse real prints.
    #[test]
    fn gcode_is_accepted_whatever_else_the_head_carries() {
        for (name, head) in [
            ("prusa", b"; generated by PrusaSlicer\nM73 P0 R2\n".to_vec()),
            ("cura", b";FLAVOR:Marlin\n;Layer height: 0.2\n".to_vec()),
            ("bare", b"M104 S210\nG28\nG1 Z0.2\n".to_vec()),
            ("latin1", b"; object Caf\xe9\nG1 X1\n".to_vec()),
            ("crlf", b"; a comment\r\nG1 X1 Y1\r\n".to_vec()),
        ] {
            opened(name, &head).unwrap_or_else(|error| panic!("{name}: {error}"));
        }
    }

    /// `--force` is what says the refusal is not wanted, and it is the only
    /// thing that does.
    #[test]
    fn opening_a_file_forced_asks_nothing_about_its_contents() {
        let path = scratch("forced").join("model.stl");
        fs::write(&path, b"solid cube\nendsolid cube\n").expect("seed the input");
        Source::open_forced(&path).expect("--force opens anything");
    }

    fn written(directory: &Path) -> Vec<String> {
        let mut names: Vec<String> = fs::read_dir(directory)
            .expect("the directory exists")
            .map(|entry| {
                entry
                    .expect("an entry")
                    .file_name()
                    .to_string_lossy()
                    .into()
            })
            .collect();
        names.sort();
        names
    }

    #[test]
    fn a_committed_sink_replaces_its_target_and_leaves_nothing_behind() {
        let directory = scratch("commit");
        let target = directory.join("part.gcode");
        fs::write(&target, "G1 X1\n").expect("seed the target");

        let source = Source::open(&target).expect("open");
        let mut sink = source.sink(&target).expect("sink");
        assert_eq!(written(&directory).len(), 2, "the temp file sits beside it");

        sink.write_all(b"G1 X2\n").expect("write");
        sink.commit().expect("commit");

        assert_eq!(fs::read_to_string(&target).expect("read back"), "G1 X2\n");
        assert_eq!(written(&directory), ["part.gcode"]);
    }

    /// A slicer hands over the only copy of its G-code, so a run that stops
    /// partway has to leave the original exactly as it was.
    #[test]
    fn a_sink_dropped_without_committing_leaves_the_target_alone() {
        let directory = scratch("abandon");
        let target = directory.join("part.gcode");
        fs::write(&target, "G1 X1\n").expect("seed the target");

        let source = Source::open(&target).expect("open");
        {
            let mut sink = source.sink(&target).expect("sink");
            sink.write_all(b"half a file").expect("write");
        }

        assert_eq!(fs::read_to_string(&target).expect("read back"), "G1 X1\n");
        assert_eq!(written(&directory), ["part.gcode"]);
    }

    /// The error names the file the caller asked for, not the temporary
    /// beside it, which only this module knows about.
    #[test]
    fn a_sink_that_cannot_be_created_names_the_target() {
        let directory = scratch("missing");
        let target = directory.join("nowhere").join("part.gcode");
        fs::write(directory.join("in.gcode"), "G1 X1\n").expect("seed the input");

        let source = Source::open(&directory.join("in.gcode")).expect("open");
        let Err(error) = source.sink(&target) else {
            panic!("the directory is missing, so the sink cannot open");
        };
        let message = error.to_string();

        assert!(message.contains("part.gcode"), "{message}");
        assert!(!message.contains(".tmp"), "{message}");
    }

    /// A slicer runs its post-processor over a file in the system temp
    /// directory, where every local user may create a name. `O_EXCL` is what
    /// says a name someone else got to first is an error rather than a file of
    /// theirs being truncated and filled with this print.
    #[cfg(unix)]
    #[test]
    fn a_temporary_is_never_opened_through_a_name_that_already_exists() {
        let directory = scratch("exclusive");
        let theirs = directory.join("their-secret");
        fs::write(&theirs, "not ours\n").expect("seed their file");
        let planted = directory.join("part.gcode.1234.tmp");
        std::os::unix::fs::symlink(&theirs, &planted).expect("plant the symlink");

        let error = create_exclusively(&planted, 0o600).expect_err("the name is taken");
        assert_eq!(error.kind(), io::ErrorKind::AlreadyExists);
        assert_eq!(
            fs::read_to_string(&theirs).expect("read back"),
            "not ours\n"
        );
        assert!(
            fs::symlink_metadata(&planted).is_ok(),
            "the link was removed"
        );
    }

    /// Refusing a taken name is only half of it: the name also has to be one
    /// nobody can take in advance, which the process id alone is not.
    #[test]
    fn a_temporary_takes_a_name_that_cannot_be_worked_out_in_advance() {
        use std::collections::HashSet;

        let target = Path::new("/spool/prints/part.gcode");
        let names: HashSet<PathBuf> = (0..64).map(|_| temporary_path(target)).collect();
        assert_eq!(names.len(), 64, "two runs drew the same name");

        let predictable = format!(".{}.tmp", std::process::id());
        for path in &names {
            assert_eq!(path.parent(), target.parent(), "{path:?}");
            let name = path.file_name().unwrap_or_default().to_string_lossy();
            assert!(name.starts_with("part.gcode."), "{name}");
            assert!(name.ends_with(".tmp"), "{name}");
            assert!(!name.ends_with(&predictable), "{name}");
        }
    }

    /// `File::create` applies `0666 & umask` and narrows afterwards, which
    /// leaves a window where another user can open the temporary — and an fd
    /// opened in that window keeps reading as the file is written.
    #[cfg(unix)]
    #[test]
    fn a_temporary_is_created_with_the_permissions_it_will_keep() {
        use std::os::unix::fs::PermissionsExt;

        let directory = scratch("private");
        let mode = |path: &Path| fs::metadata(path).expect("stat").permissions().mode() & 0o777;

        // The creating call itself, with nothing done afterwards: no group or
        // other bits exist at any point.
        let private = directory.join("private.tmp");
        let file = create_exclusively(&private, 0o600).expect("create");
        drop(file);
        assert_eq!(mode(&private) & 0o077, 0, "created readable by others");

        // And a target that is readable by others gets a temporary that is
        // too, whatever the umask narrowed it to on the way in.
        let target = directory.join("part.gcode");
        fs::write(&target, "G1 X1\n").expect("seed the target");
        fs::set_permissions(&target, fs::Permissions::from_mode(0o644)).expect("chmod");
        let (_, temporary) =
            create_temporary(&target, intended_mode([target.as_path()])).expect("temporary");
        assert_eq!(mode(&temporary), 0o644);
    }

    /// `rename` replaces a symbolic link itself, not the file it stands for,
    /// so a slicer directory pointed at shared storage would keep the
    /// unprocessed G-code and lose the link.
    #[cfg(unix)]
    #[test]
    fn a_symlinked_target_is_followed_to_the_file_it_stands_for() {
        let directory = scratch("symlink");
        let real = directory.join("real.gcode");
        let link = directory.join("part.gcode");
        fs::write(&real, "G1 X1\n").expect("seed the target");
        std::os::unix::fs::symlink(&real, &link).expect("link it");

        let source = Source::open(&link).expect("open");
        let mut sink = source.sink(&link).expect("sink");
        sink.write_all(b"G1 X2\n").expect("write");
        sink.commit().expect("commit");

        assert_eq!(fs::read_to_string(&real).expect("read back"), "G1 X2\n");
        let kind = fs::symlink_metadata(&link).expect("stat").file_type();
        assert!(kind.is_symlink(), "the link was replaced by a regular file");
        assert_eq!(fs::read_link(&link).expect("read the link"), real);
    }

    /// A rename publishes a new inode, so the other names for the old one keep
    /// the file as it was sliced. Nothing in `std` can move them, so it is
    /// said rather than done quietly.
    #[cfg(unix)]
    #[test]
    fn replacing_a_file_says_what_it_cannot_carry_over() {
        let directory = scratch("hard-links");
        let target = directory.join("part.gcode");
        fs::write(&target, "G1 X1\n").expect("seed the target");

        let source = Source::open(&target).expect("open");
        let quiet = source.sink(&target).expect("sink");
        assert!(quiet.warnings().is_empty(), "{:?}", quiet.warnings());
        drop(quiet);

        fs::hard_link(&target, directory.join("also.gcode")).expect("hard link");
        let sink = source.sink(&target).expect("sink");
        let warning = sink.warnings().join("\n");
        assert!(warning.contains("hard-linked"), "{warning}");
        assert!(warning.contains("part.gcode"), "{warning}");
    }

    /// Every reader here strips a trailing `\r` and every transform writes a
    /// bare `\n`, so putting the file's own ending back is the only thing that
    /// keeps a Windows-authored file byte-identical where nothing was changed.
    #[test]
    fn a_rewrite_puts_back_the_line_endings_the_file_arrived_with() {
        for (label, original) in [
            ("endings-lf", "G1 X1\nG1 X2\n"),
            ("endings-crlf", "G1 X1\r\nG1 X2\r\n"),
            ("endings-lf-open", "G1 X1\nG1 X2"),
            ("endings-crlf-open", "G1 X1\r\nG1 X2"),
        ] {
            let input = scratch(label).join("in.gcode");
            fs::write(&input, original).expect("seed the input");

            let source = Source::open(&input).expect("open");
            let mut sink = source.sink(&input).expect("sink");
            // What a transform does: one line at a time, terminated with a
            // bare newline whatever the file used.
            for line in original.lines() {
                writeln!(sink, "{line}").expect("write");
            }
            sink.commit().expect("commit");

            assert_eq!(
                fs::read_to_string(&input).expect("read back"),
                original,
                "{label}"
            );
        }
    }

    #[test]
    fn a_source_can_be_read_twice_and_written_somewhere_else() {
        let directory = scratch("rewrite");
        let input = directory.join("in.gcode");
        let output = directory.join("out.gcode");
        fs::write(&input, "; layer_height = 0.2\nG1 Z0.2\nG1 Z0.4\n").expect("seed the input");

        let source = Source::open(&input).expect("open");
        assert!(!source.is_binary());
        let survey = source.survey().expect("survey");
        assert_eq!(survey.layers, 2);

        let sink = source.sink(&output).expect("sink");
        let copied = source
            .rewrite(sink, |mut reader, writer| {
                let count = io::copy(&mut reader, writer)?;
                Ok(count)
            })
            .expect("rewrite");

        assert_eq!(
            copied as usize,
            fs::metadata(&input).expect("stat").len() as usize
        );
        assert_eq!(
            fs::read_to_string(&output).expect("read back"),
            fs::read_to_string(&input).expect("read the input")
        );
    }
}
